### ISSUE TITLE
Post processing

### ISSUE THREAD

**Issue by mehdi-mm** [mozvip/Sick-Beard#112]
Le post processing renomme bien mes fichiers, les déplace mais les mets à la racine du folder Series et pas dans le répertoire saison !
une config a changé ?

**Comment by an0Nym0us63** [comment]
oui ton rename pattern met toi en custom

voici le mien

Saison %0S/%SN - S%0SE%0E - %EN

**Comment by mehdi-mm** [comment]
merci
Post processing - Naming - Check Custom air by date - name pattern = Custom - Saison %0S/%SN - S%0SE%0E - %EN

--> this pattern is invalid 

Persi moi j'aimerais avoir ça pour rester comme avant : Californication - 6x11 - The Abby
