### ISSUE TITLE
comment contribuer ?

### ISSUE THREAD

**Issue by Nonobis** [mozvip/Sick-Beard#129]
Bonjour sarakha63,

Je me suis permis de forker le projet pour rajouter une option qui me manquait sur l'écran MassEdit. D'après mes tests cela fonctionne. Il est maintenant possible de modifier la langue des metadata par le biais de cet écran. 

J'ai mis pas mal de commit car je n'ai pas l'habitude du python, et j'ai eu quelques difficultés à me repérer dans le code. Je suis un développeur .Net toutefois donc j'ai pu m'en sortir ..
Comment faire pour en faire bénéficier ton fork ?

**Comment by brinbois** [comment]
Il faut que tu fasse une pull request, pour que sarakha63 puis l’intégrer ou pas.

**Comment by Nonobis** [comment]
je fais le pull request de quel manière ?

**Comment by brinbois** [comment]
Depuis ton fork, tu a un bouton pull request ( de la même manière que tu a fait le fork)

**Comment by Nonobis** [comment]
C'est fait. Merci Brinbois

**Comment by an0Nym0us63** [comment]
PS: je vais prendre apres avoir testé.

Mais attention ne faites plus de request sur concernant les ecrans dans les prochains jours.

Je suis en train de refaire toute l'interface a la manière de mr-orange pour lui donner un coup de jeune.

Mais cool, n'hésitez pas a faire plein de pull requests
