### ISSUE TITLE
Demande d'ajout d'une  chaine de recherche

### ISSUE THREAD

**Issue by pedro2d10** [mozvip/Sick-Beard#133]
Bonjour,

Merci pour cette magnifique version de Sick Beard.

J'ai souhaité ajouter ma contribution à ce projet mais malheureusement mes compétence en python sont limité et j'en est fait planter mon Sick Beard.

Voila donc ma requête (toute simple) si quelqu'un veux bien s'atteler à la tâche:

J'aurais souhaité que Sick Beard puisse rechercher un épisode avec la syntaxe suivante: "Episodename SXX EXX".

Actuellement il recherche déjà bien "EpisodeName SXXEXX" mais j'ai quelques série ou il y à un espace entre le numéro de la saison et le numéro de l'épisode.

Voila donc ma requête. 

Merci à tous pour votre aide.

**Comment by an0Nym0us63** [comment]
fait dans le nouveau fork
