### ISSUE TITLE
Synology and hibernate

### ISSUE THREAD

**Issue by lodoss5** [mozvip/Sick-Beard#134]
I have the feeling my synology no more comes to hibernate.
Is it due to this log which happens every 10 min even if Trakt is not enable in notifications?
May-25 00:40:30 DEBUG    TRAKTWATCHLIST :: Starting new thread: TRAKTWATCHLIST

**Comment by an0Nym0us63** [comment]
even tough this log wont appear, sickbeard makes a post processing search every 10 mins .

Did you desactivate post processing.

en gros je comprens ton besoin, mais sickbeard fais plein d'autres choses, post processing toutes les 10 minutes, rss searc toutes les heures par defaut backlog limited toutes les 2 h.

Donc entre empecher l'hibernation, et le faire s'arréter et reveiller toutes les heures je ne sais pas ce qui est le mieux. Auquel cas tu peux tester d'éditer le fichier _init-.py et desactiver le lancement de ce thread pour etre sur que sans cela il hiberne

**Comment by lodoss5** [comment]
Oui j'ai déactivé le post processing et en effet normalement c'était 1 fois par heure que Sickbeard faisait quelquechose dans ma config avant l'arrivée de ce nouveau thread.
Après arrêt et réveil toutes les heures je ne sais pas non plus si c'est mieux que de ne jamais se mettre en veille.
Ne serait-il pas mieux de ne lancer ce thread que si Trakt est activé ?

**Comment by an0Nym0us63** [comment]
Oui ca sera fait dans les prochaines maj

---

De: lodoss5 
Envoyé: sam., 25/05/2013 12:41
A: mozvip/Sick-Beard Sick-Beard@noreply.github.com
CC: sarakha63 sarakha_ludovic@yahoo.fr
Objet: Re: [Sick-Beard] Synology and hibernate (#134)

**Comment by lodoss5** [comment]
Super :)

**Comment by an0Nym0us63** [comment]
c'est fait sur le new fork

---

 De : lodoss5 notifications@github.com
À : mozvip/Sick-Beard Sick-Beard@noreply.github.com 
Cc : sarakha63 sarakha_ludovic@yahoo.fr 
Envoyé le : Dimanche 26 mai 2013 14h22
Objet : Re: [Sick-Beard] Synology and hibernate (#134)

Super :)

**Comment by an0Nym0us63** [comment]
fait dans le nouveau fork
