### ISSUE TITLE
Post processing

### ISSUE THREAD

**Issue by mehdi-mm** [mozvip/Sick-Beard#135]
Hello
Comme tu as fermé le post avant que je puisse répondre ...
Je te remets le lien : https://github.com/mozvip/Sick-Beard/issues/112
Parce que je pense que tu dois plus etre notifié.

Kratos42 opened this issue 6 days ago
Post processing
Edit
No milestone No one is assigned
Le post processing renomme bien mes fichiers, les déplace mais les mets à la racine du folder Series et pas dans le répertoire saison !
une config a changé ?
2 participants    

 sarakha63 commented 6 days ago
oui ton rename pattern met toi en custom

voici le mien

Saison %0S/%SN - S%0SE%0E - %EN
Closed
 sarakha63 closed the issue 6 days ago

 Kratos42 commented a day ago 
merci
Post processing - Naming - Check Custom air by date - name pattern = Custom - Saison %0S/%SN - S%0SE%0E - %EN

--> this pattern is invalid

Persi moi j'aimerais avoir ça pour rester comme avant : Californication - 6x11 - The Abby

**Comment by an0Nym0us63** [comment]
Il est valide il be faut pas le mettre dabs custom air by date . Mais dans naming pattern en choisissant custom dans la liste.

**Comment by mehdi-mm** [comment]
ok nickel
