### ISSUE TITLE
Recherche 

### ISSUE THREAD

**Issue by mehdi-mm** [mozvip/Sick-Beard#136]
Hello j utilise ton fork depuis qques temps et comme le but c'est pas se soucier de ce qu'il se passe j'ai pas remarqué que depuis peu j'ai qques soucis.
Je suis un utilisateur particulier je pense dans le sens où je m'intéresse pas au français ni pour l'audio ni pour les sub.
Cela dit je trouve cool le fait de pouvoir choisir notamment pr les simpsons que j'aime qu'en fr.
Mes pblms : 
- je trouve pas certains épisodes pourtant ils sont bien sur T411
- j'en trouve certains mais ya du VOSTFR je peux les zapper via une expression reguliere qque part et prendre plutot la version full EN ? Le Ignore Words par ex ?

Merci d'avance

Dans les logs je vois Timed out while loading URL http://thepiratebay.se/search/
J'imagine tu as pas eu le temps de changer avec le nvo nom de domaine ?

**Comment by an0Nym0us63** [comment]
Les timeout ne sont pas lies au nom de domaine mais simplement un vrai timeout.  Qui peut arriver si sick recherche  et quec ta ligne dl deja.

Oui les ignore words pourront aider pour le vostfr
