### ISSUE TITLE
Tri des séries n'est plus sauvegardé

### ISSUE THREAD

**Issue by lodoss5** [mozvip/Sick-Beard#139]
J'ai pour habitude de trier mes séries avec la colonne "Next Ep" et avant ce tri était sauvegardé (quand j'appuyais sur le logo SickBeard pour me mener à la homepage mon dernier tri sélectionné était repris), ce n'est plus le cas : maintenant quand on clique sur le logo, on retrouve un tri par défaut qui est toujours Active + Show.

**Comment by an0Nym0us63** [comment]
c'est normal et c'est lié au rajout du search. Et malheureusement ca restera comme ca  a savoir qu'en un clic tu retris comme tu veux
