### ISSUE TITLE
Couleur du compteur d'épisodes

### ISSUE THREAD

**Issue by lodoss5** [mozvip/Sick-Beard#140]
Serait-il possible d'avoir une couleur autre que vert dans la colonne Downloads de la homepage pour les séries ou il manque des épisodes ?

**Comment by an0Nym0us63** [comment]
lodoss ce fork n'est plus suivi.

pourquoi pas bonne idée

**Comment by an0Nym0us63** [comment]
fait dans le nouveau fork
