### ISSUE TITLE
"NZBClub failed : timed out" dans les logs

### ISSUE THREAD

**Issue by narfight** [mozvip/Sick-Beard#142]
Bonjour,

J'ai le log qui est rempli d'erreur pour NZBClub mais je ne le vois pas dans les provider !

> 2013-06-11 00:52:06.735579 SEARCHQUEUE-BACKLOG-73141 :: Searching from NZBClub failed : timed out

Cordialement,
Narfight

**Comment by an0Nym0us63** [comment]
ce n'est plus le bon git pour les questions.

Mais je vais répondre.

Nzbclub est utilisé par binnews.

Et effectivement si tu lances une recherche alors que ton nas ou autre est en train de téléchargé tu peux avoir des timeout (logique), une solution est de configurer ton client de téléchargement pour ne pas utiliser 100% de la bande passante mais 90 % par exemple
