### ISSUE TITLE
Nom épisodes FR

### ISSUE THREAD

**Issue by mehdi-mm** [mozvip/Sick-Beard#143]
Bonjour
comment faire pr avoir le nom des épisodes en FR quand on veut un show en français si la fonction est implémentée bien sur

**Comment by an0Nym0us63** [comment]
Tu utilises metadata lang fr. Et force full update des shows concernes et si tvdb les a en fr tu les aura en fr

---

De: Kratos42 
Envoyé: dim., 16/06/2013 22:52
A: mozvip/Sick-Beard Sick-Beard@noreply.github.com
Objet: [Sick-Beard] Nom épisodes FR (#143)
