### ISSUE TITLE
Rename option

### ISSUE THREAD

**Issue by ClementHector** [mozvip/Sick-Beard#154]
Bonjour,
Est-il possible d'ajouter une Pattern dans l'épisode naming ( ex %L ) pour pouvoir lors du renommage inscrire la langue de l'épisode.
Moins important, on pourrait aussi envisager que lors du scan, il repère certain mot pour renseigner le langage audio de l'épisode.( Par exemple si il vois FRENCH dans le nom, il le passe en audio francais )
Si vous avez besoin d'un coups de main, je sais codé en python, dite moi dans quelle coin chercher.

**Comment by an0Nym0us63** [comment]
mauvais git la suit de ce projet est sur le git sarakha63
