### ISSUE TITLE
Impossible to launch sickbeard on my NAS

### ISSUE THREAD

**Issue by laellyo** [mozvip/Sick-Beard#23]
Hi,

I'm a french follower of your work on nas-forum.com. Great job guys! :) 
Unfortunately, I can't launch your custom version of sick-beard on my NAS... To begin, some information about the context :
NAS : Synology DS212j
Community repository : synocommunity
GIT url : git://github.com/mozvip/Sick-Beard.git
GIT branch : master
I followed adviced on this url : http://www.nas-forum.com/forum/topic/33586-presentation-sickbeard-vovf-avec-sous-titre-binnews-t411-etc;/

Before to install this version, I uninstall the other available version of sickbeard on syno-community repository.

Any error during the installation, but impossible to start it. I find any error information in the logs... :(

If you need some more information, don't hesitate to contact me.
Thanks in advance for you help!

Laellyo

**Comment by an0Nym0us63** [comment]
Did you have the synology package gît installed before. Lots of people used the sickbeard custom spk to install this version without any problems. What doesnt work for you? Does the package  launch when you click launch? If so what shows the journal? 

Envoyé de mon iPhone

**Comment by an0Nym0us63** [comment]
You CAN answer in french if you think you can ex plain in a better way.

Envoyé de mon iPhone

**Comment by laellyo** [comment]
Yes I installed GIT package (it's impossible to install your sickbeard package without GIT :) )
I clicked on launch 3 or 4 times and after some seconds, the service status was still "stop". 
As I found any error logs, I finally desinstall and reinstall sickbeard. It's working now...

So, I will close my Issue.
Thanks for you quick reply Sarakha!

Laellyo

**Comment by an0Nym0us63** [comment]
You mean you reinstalled the official one or our fork?

If so dont hésitate to give your feedbacks. Hope you Will enjoy accessing  tvshow un french auto downloaded

Envoyé de mon iPhone

**Comment by laellyo** [comment]
I reinstall your fork and now, it's working perfectly! :)
Don't worry, I will give you my feedback after using your fork during some days.

**Comment by an0Nym0us63** [comment]
Thanks you CAN leave a message on the forum to show others its working.  Usually we used to install it by ssh commands. I think you are one of the first to install it With Diaouls spk

Envoyé de mon iPhone
