### ISSUE TITLE
Add show default settings

### ISSUE THREAD

**Issue by mehdi-mm** [mozvip/Sick-Beard#24]
Quand on fait un add show ça serait cool de pouvoir mettre par défaut un language pr les metadata
J'ai fait un Add existing show, il boucle sur tous mes show, j'ai fait save default mais à chaque fois il me prend audio en fr et statut Skipped alors que j'avais sauvé EN et wanted

**Comment by an0Nym0us63** [comment]
Normalement si tu las sauvé il devrait te le prendre. Je vais regarder, je regarde ce week end

Envoyé de mon iPhone

**Comment by mehdi-mm** [comment]
Ok
jai bouclé sur ts mes anciens show et jai fait sauve 10 fois et ca a pas marche une seule fois 

Jai pas trouve comment poste de request (dsl) mais jaouter pirate bay en provider ca serait top

Merci a toi

**Comment by an0Nym0us63** [comment]
Pirate bay c prevue, je regarderais pour le save.

Si tu connais le ssh je veux bien une copie de ton config ini que tu trouves dans le dossier volume1/@appstore/sickbeard-custom/var

Après un save
.

Ps quand tu saves il te marque config saves?

Envoyé de mon iPhone

**Comment by mehdi-mm** [comment]
oui il me met bien config saved to ...

Le config.ini ici http://uptobox.com/xwoh1518g52u

Curieusement cette fois ça a marché !!

Jai voulu ajouter une serie bidon juste pr voir et c'est ok.

Merci pr ta reactivite.

PS : ca marche aussi pr un add existing. Bon je sais pas ce que j'ai b***\* !

**Comment by an0Nym0us63** [comment]
ok je regarderais surement ce week end. pour pirate bay peux tu faire une autre issue stp pour qu'on ai t un suivi

**Comment by an0Nym0us63** [comment]
attention supprime le lien car les mots de passe ne sont pas codés dans le fichier ils sont en clair

**Comment by an0Nym0us63** [comment]
ton soucis c juste sur les metadata ? pour le audio lang et le reste c bon? SI c ca c normal pour les metadata il n'ya pas de paramètre mais effectivement je peux le rajouter histoire que chacun sauve son paramètre par defaut

**Comment by mehdi-mm** [comment]
jai supprime mes pwd avant de te filer mon fichier mais merci de me prevenir.

Le save metadata avec un default est par contre tjrs un truc qui serait sympa.

Ds mon cas je prends tout en anglais sauf qque trucs que je prefere en francais. Du coup je prefere pouvoir choisir ma langue par defaut pour tout.

Cela dit cest que mon point de vue

Je viens de voir ton dernier post et oui c'est otut bon. et si tu peux ajouter une bouton save ca serait top

**Comment by an0Nym0us63** [comment]
Pas de soucis ça sera fait. Ps ton pwd t411 était en clair d'où mon message

Envoyé de mon iPhone

**Comment by mehdi-mm** [comment]
ah oui en effet
