### ISSUE TITLE
add gks.gs provider

### ISSUE THREAD

**Issue by filoune** [mozvip/Sick-Beard#26]
est ce que vous pourriez ajoutez gks.gs ( https://gks.gs/ )  comme torrent provider. il est plus ' sécurisé '  vis a vis  de hadopi & co  ainsi que bien d'autres  + ...

en espérant un retour positif 

merci ;)

**Comment by an0Nym0us63** [comment]
aurais tu une invit pour ce site. Sans ca difficile de concevoir la creation d'un provider.

SI c'est le cas contact moi par mp

**Comment by filoune** [comment]
j'en aurai une dans 1 semaine. je te tien au courant

**Comment by an0Nym0us63** [comment]
Ok pense a moi c'est un près requis pour envisager un provider tu t'imagines bien que sans accès au site c dur lol

Envoyé de mon iPhone

**Comment by filoune** [comment]
oui c est sur lol 

regarde tes MP sur nas-forum  , tu devrais en avoirs une normalement ;)

**Comment by foXaCe** [comment]
effectivement un scraper pour ce tracker serait le bienvenue

**Comment by romanocry** [comment]
CE scraper/provider est deja dispo sur un autre forks.

Ici -->  https://github.com/Kyah/Sick-Beard/blob/kyah/sickbeard/providers/gks.py

j'ai demander a l'auteur de venir faire un tour ici, histoire de voir s'il peux participé a l'ajout du provider

**Comment by foXaCe** [comment]
merci je vais voir pour avec sarakha63 si il est forme pour l'intégrer

**Comment by romanocry** [comment]
https://github.com/romanocry/Sick-Beard

branche development

j'essaie de faire ca a la main :)
j'y connais rien... on verra bien :)

**Comment by foXaCe** [comment]
Ok fais-moi un retour si ça marche

**Comment by jgoret** [comment]
Bonjour,
Je suis l'auteur du patch pour le sickbeard original, je vais regarder dès aujourd'hui pour l'intégrer a ce fork que je ne connaissait pas et qui m'intéresse par ses fonctionnalités! 

Je vous tiens au courant de mes avancées via cette issue

**Comment by foXaCe** [comment]
Ok .j’ai réussi à intégrer ton fork mais il manque la partie pour entrer son username et password

**Comment by romanocry** [comment]
Cool :) Kyah est donc parmis nous :) 
foXaCe, gks demande plutot ton code API.

J'ai test le forks de kyah, malheureusement, ca ne fonctionne pas chez moi..

**Comment by jgoret** [comment]
Donc, j'ai refait mon job d'intégration de GKS.GS à partir du fork de mozvip et j'ai une première version a proposer mais elle ne permet pour le moment que de récupérer les nouveaux épisodes en VOSTFR. (voir ce commit : https://github.com/Kyah/Sick-Beard/commit/79cb01cede7f4a1f19846a93d2911ecdd573ca5a ).

Je vais me pencher sur les solutions pour choper le VO et le VF, ainsi que la possible implémentation du backlog via les RSS proposés. J'ai vu que normalement avec cette version il y a la possibilité de choisir entre VO et VF, y'aurais t'il un provider qui se sert de ces informations sur lequel je pourrais me baser pour améliorer le mien?

Je ferais un Pull Request une fois que j'aurais ajouté au minimum l'intégration VO/VF.

**Comment by foXaCe** [comment]
le scraper t411 est la base que tu dois prendre

**Comment by jgoret** [comment]
OK merci bien. En effet y'a pas mal de changements a appliquer a mon code !
je regarde ça dès que possible!

J'ai commencé a analyser les flux que fourni GKS et je pense que j'ai tout
ce qu'il me faut pour proposer les langues fr/vo et le backlog.

**Comment by jgoret** [comment]
Alors me revoila avec une première version qui va enfin récupérer correctement les épisodes VF ou VO selon la conf du programme. J'ai encore quelques améliorations a apporter afin qu'il puisse chercher de la SD comme de la HD sans problèmes.

Vous pouvez trouver le code ici : https://github.com/Kyah/Sick-Beard/tree/gks_gs_dev :) Il est surement amener a évoluer dans les quelques jours a venir. Si quelqu'un veux bien m'aider à le tester sur la longueur (avec de nouveaux épisodes qui sortent, même si la VO n'est pas la catégorie la mieux fournie sur GKS...) je suis évidement preneur!

**Comment by romanocry** [comment]
Je test ca tout de suite ;)

si tu peux juste ajouté cette modif pour t411 en même temps :) Ca marche vraiment mieux !
http://www.nas-forum.com/forum/topic/33586-presentation-sickbeard-vovf-avec-sous-titre-binnews-t411-etc;/?p=1319186090

**Comment by foXaCe** [comment]
ok nickel j'attend que tu merge les dernieres modif faite sur ce fork et je test le tiens

**Comment by an0Nym0us63** [comment]
es tu sur que GKS utilise seulement des numérotations  du style SxxExx car j'ai vu que tu as squizzé les numérotations du genre 5x03 etc...

**Comment by jgoret** [comment]
Oui je l'ai fait volontairement car il n'y a pas de nommage de ce type sur GKS, mais je peux le rajouter très rapidement si cela est vraiment nécessaire.

**Comment by an0Nym0us63** [comment]
Non ok pas de soucis.

;)

---

De: Kyah 
Envoyé: mer., 15/05/2013 10:08
A: mozvip/Sick-Beard Sick-Beard@noreply.github.com
CC: sarakha63 sarakha_ludovic@yahoo.fr
Objet: Re: [Sick-Beard] add gks.gs provider (#26)

**Comment by foXaCe** [comment]
j'ai ce bug qui reviens pas mal

Error while searching gks, skipping: 'NoneType' object has no attribute 'lower'

**Comment by jgoret** [comment]
Une première remontée :)

Tu pourrais regarder les logs debug et me donner au minimum la/les URL que
le sickbeard tente de parser? (sans ta clé dedans évidement...) Je connais
la ligne incriminée, mais il me faudrait une page pour que je puisse
débuguer.

2013/5/15 foXaCe notifications@github.com

> j'ai ce bug qui reviens pas mal
> 
> Error while searching gks, skipping: 'NoneType' object has no attribute
> 'lower'
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mozvip/Sick-Beard/issues/26#issuecomment-17935077
> .

## 

Goret Julien
Ingénieur Système - Atos Worldline
jgoret@gmail.com
+33 (0) 6 11 76 87 67

**Comment by foXaCe** [comment]
File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/search.py", line 353, in findSeason
    curResults = curProvider.findSeasonResults(show, season)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/providers/generic.py", line 307, in findSeasonResults
    itemList += self._doSearch(curString, show=show, season=season)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/providers/gks.py", line 91, in _doSearch
    if "vostfr" in title.lower() or "aucun resultat" in title.lower():
AttributeError: 'NoneType' object has no attribute 'lower'

j'ai ça de le debug et la série elle s'appelle Revolution

**Comment by an0Nym0us63** [comment]
rhaaaaa kyah je viens de voir ta signature...........;

Mon dieu un concurrent lol

**Comment by an0Nym0us63** [comment]
kyah si tu le veux tu peux devenir un codeur du sisck et du couch car plus on est mieux c'est

ya plein d'idée qui serait bien

dis moi si tu veux si tu penses avoir les compétences (je pense que oui) et le temps que tu pourrais y consacrer

ya deux grosses fonctionnalités majeures que j'aimerais implenter

**Comment by foXaCe** [comment]
Pour éviter tout doute le key il faut bien utiliser celle du Flux RSS de téléchargement direct et pas celle de AutoGet

**Comment by jgoret** [comment]
Je confirme, c'est bien cette clé là! Je regarde un peu pour faire des tests et reproduire le problème.

@sarakha63 Ca me tente assez oui! Je connais pas encore très bien le cœur de sickbeard. Je n'ai pour le moment touché qu'aux choses "faciles" que sont les providers et les metadata mais je veux bien me pencher sur quelques sujets majeurs!

**Comment by foXaCe** [comment]
le manual search n'est pas integrer ?

**Comment by romanocry** [comment]
euh... PassKey ou AuthKey ? pour GKS....
A l'instant, il ne me trouve pas le NCIS S10E24 :(

**Comment by jgoret** [comment]
Il s'agit de la AuthKey disponible dans votre profil ( https://gks.gs/m/account/ )*

@foXaCe qu'est ce que tu entend pas manual search? Je n'arrive pas a reproduire ton erreur, tu pourrais me faire un petit topo sur ce que tu fais pour arriver à cette erreur?

**Comment by foXaCe** [comment]
si je selectionne seulement gks comme provider et que je fais un manual search sur un épisode j"ai ca

SEARCHQUEUE-BACKLOG-248835 :: Error while searching gks, skipping: 'NoneType' object has no attribute 'lower'
SEARCHQUEUE-BACKLOG-248835 :: No NZB/Torrent providers found or enabled in the sickbeard config. Please check your settings.

**Comment by romanocry** [comment]
auth key !!! merci @Kyah ;)

ah bah en fait, c'est bien ce que j'avais mis.. :/

mai-15 15:43:18 INFO     SEARCHQUEUE-RSS-SEARCH :: No needed episodes found on the RSS feeds
mai-15 15:43:18 INFO     SEARCHQUEUE-RSS-SEARCH :: Searching all providers for any needed episodes
mai-15 15:43:18 INFO     SEARCHQUEUE-RSS-SEARCH :: Beginning search for new episodes on RSS
mai-15 15:43:18 INFO     SEARCHQUEUE-RSS-SEARCH :: Changing all old missing episodes to status WANTED
mai-15 15:34:55 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Unable to find a download for NCIS - 10x24 - Damned If You Do
mai-15 15:34:47 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Searching T411 for NCIS - 10x24 - Damned If You Do
mai-15 15:34:47 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Searching gks for NCIS - 10x24 - Damned If You Do
mai-15 15:34:47 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Searching for NCIS - 10x24 - Damned If You Do
mai-15 15:34:47 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Searching for download for NCIS - 10x24 - Damned If You Do

**Comment by an0Nym0us63** [comment]
pour moi il y a deux gros chantier

1) gestion des langues a la manière des qualités dans couch (je veux fr et en mais je prefere fr donc il cherche fr si il trouve pas il cherche en mais continue a chercher fr et si il trouve fr il arrete)

2) gestion de liste de liens par episode comme couch ( facile a faire je pense il suffit de recup tous les liens quil considere valide avant qu'il choisissse celui quil va snatched, de les stocker en base avec lien, provider etc.... toutes les infos sont dispo facilement, et de faire un systeme de popup pour que quand tu cliques sur un episode il te propose tous les liens possibles comme ca si le premier echoue car irréparable ou autre ben tu as le choix d'une liste pour en lancer un autre)

**Comment by jgoret** [comment]
@sarakha63 Ok, le premier point était aussi dans mes idées/envies donc je regarderais surement si je trouve un solution à ca, je pense pas que ce soit très difficile mais c'est à valider.

@foXaCe tu pourrais me fournir ton fichier de log qui devrait être dispo dans /volume1/@appstore/sickbeard-custom/var/SickBeard/Logs pour que je puisse creuser un peu plus? J'ai tenté de faire des recherches manuelles de tout les épisodes mais pas réussi a reproduire ton erreur.

**Comment by foXaCe** [comment]
file moi ton mail

**Comment by jgoret** [comment]
jgoret@gmail.com

**Comment by foXaCe** [comment]
ta recu mon mail ?

**Comment by jgoret** [comment]
@foXaCe Oui je suis justement en train de tester. Ce qui m’embête c'est que je n'arrive pas à reproduire l'erreur que tu as. Peut-être que cela viens du fait que je teste mon code sur une machine Windows et pas un syno comme toi... Je vais tenter de faire d'autres tests mais je n'ai pas de machines comme celle-ci pour valider mon code! Pourrais-tu au moins me donner la version de python que tu utilise?

@romanocry Tu recherche la série en quelle langue? Si c'est de la VO ça ne m'étonne pas qu'il ne trouve rien car il n'y sont pas sur GKS ;)

**Comment by foXaCe** [comment]
ton scraper marche sur le syno de sarakha63 et je refais toutes l'install de mon sickbeard et je te tiens au jus

**Comment by romanocry** [comment]
@Kyah euh bah la vostfr tant qu'à faire.
La version dispo en vostfr est considéré comment ? VO ? VF ? VOSTFR?

**Comment by an0Nym0us63** [comment]
non je confirme ca marche sous windows mais pas sur syno

**Comment by an0Nym0us63** [comment]
kyah pour le vostfr je te propose d'adapter ton code en disant si demandé VO et sous titre activé dans ce cas je le prends

**Comment by an0Nym0us63** [comment]
python 2-7-3

on a pas le choix c'est la seule dispo en paquet sur syno pour l'instant

pour moi le soucis ne vient pas du lower en tant qu tel mais avant il doit ya voir avatn kkch qui fait que ton item se retrouve null

**Comment by romanocry** [comment]
VOSTFR > VO (+dwl STFR)
Perso, je prend jamais de VF

Sous une seedbox (archlinux) ca cherche, sans prendre :)
GKS devant T411, trouve pas chez GKS (alors que dispo) mais prend chez T411

**Comment by an0Nym0us63** [comment]
tout simplement car sur T411 il ne sont pas forcement bien référencé VOSTFR dans le titre.

**Comment by romanocry** [comment]
hummm, j'avoue mon incompréhension...
S'il est "mal nommé", il ne devrais donc pas le prendre, non ?

**Comment by an0Nym0us63** [comment]
ben non il prend car justment pour lui c un vo. Car selon moi VO c'est pas vostfr

Theoriquement notre version gere vf vo mais pas vostfr

**Comment by an0Nym0us63** [comment]
@kyah pourquoi tu utilises beautifulsoup pour parser une page rss pourquoi tu utilises pas un parser xml

**Comment by jgoret** [comment]
Alors j'ai forcé les VOSTFR a ne pas être pensés parce qu'à 100% les sous-titres sont incrustés donc ça ne colle pas trop avec la logique de télécharger les .srt a coté. Mais il est tout a fait envisageable d'autoriser les VOSTFR si les sous-titres sont activés.

Je confirme que mon code tourne en Windows et sur une Ubuntu Server, je penche pour un truc qui tourne pas bien avec BeatifulSoup sur le syno, je vais creuser pour contourner le problème en repartant sur mon parsing avec minidom.

**Comment by an0Nym0us63** [comment]
mais dans tous les cas pour l'instant gks est buggué

**Comment by an0Nym0us63** [comment]
@Kyah 
https://gks.gs/rdirect.php?type=search&q=American+Horror+Story%2BS02&category=12&ak=19c9bc4576258f64642d36dcd4679336&order=desc&sort=normal&exact

jusque la le syno y arrive

**Comment by jgoret** [comment]
C'est pour ca que je penche sur une galère de BeautifulSoup, je repart sur mon code avec minidom et je vous le met a dispo au plus vite! (sans la gestion des VOSTFR pour le moment déjà)

**Comment by an0Nym0us63** [comment]
ben avec minidom aucun soucis je pense avant je parser nzbmatrix et newzbin avec ca ou element tree.

PAr contre c'est marrant beautifulsoup marche bien sur un parsage web sur les autres scraper mais la on dirait quil voit rien il ramene systematiquement un titre null. j'ai meme commité en enlevant le lower pour voir et pareil.

@Kyah  100% d'accord avec toi car pour moi les sous titre c'est a coté raison pour laquelle je me suis pas embete a faire VO/vostfr/vf mais seulement VO/VF. MAis apres tout on peut les laisser passer

**Comment by an0Nym0us63** [comment]
vostfr c faciel quand tu parse tu dis si ya vostfr et que je suis en vo et que j'ai activé les sous titre ok j'accepte sinon squizz

**Comment by an0Nym0us63** [comment]
@kyah c'est pour ca que je t'ai directmeent parlé d'un parser xml c mieux

**Comment by romanocry** [comment]
effectivement, la logique "sur GKS" il n'y a pas/peu de VO only.. mais il y a VF et VOSTFR. 
C'est donc là que ca pose probleme.

**Comment by an0Nym0us63** [comment]
ben la justement si tu veux vo il ya d'autres providers, car moi perso je trouve dommage de laisser passer de la vostfr alors qu'une vo avec sous titre fera pareil

zt 80% du temps les incrustés sont soit petit soit pixélisés etc....

mais comme je 'lai dis c facile de le lasiser passer dans le cas ou kkun demande vo et a activé les sous titres. Après le réel intéret je sais pas

**Comment by romanocry** [comment]
jusqu'a maintenant, j'utilisais les NG avec SB+sabnzbd+ @home :)
J'ai maintenant une seedbox, et T411+GKS, et il n'y a pas de VO only, donc je me rabat sur le VOSTFR :)
Mais bien evidement, s'il y a, en torrent, du VO, je prend sans hésiter ;)
Subliminal s'occupera du reste

**Comment by jgoret** [comment]
@sarakha63 le code avec minidom existe déjà dans mes anciennes version, je le teste actuellement pour l'éprouver un peu sur mes PF de tests (histoire d'avoir au moins aussi bien qu'actuellement de mon coté...)

Je regarde juste après pour laisser passer la VOSTFR en fonction des sous-titres (personnellement je prend quasiment que les épisodes VOSTFR de GKS donc je veux bien activer cette fonctionnalité!)

**Comment by romanocry** [comment]
Moi je veux :) 
Après tout, c'est moi qui t'es fait venir ici .. :) xD

**Comment by jgoret** [comment]
Hop nouveau commit pour l'utilisation du minidom : https://github.com/mozvip/Sick-Beard/pull/89

**Comment by an0Nym0us63** [comment]
pas de soucis

rhaaa je peux pas merged auto saloperie de git lol

**Comment by an0Nym0us63** [comment]
mais pour le vostfr je veux bien qu'il passe dans le cas d'un config VO + sous titre activé. MAis je ne veux pas rajouter vostfr au choix des audio

**Comment by an0Nym0us63** [comment]
bon banco j'ai fais le merge a la main et ca marche sur syno

**Comment by an0Nym0us63** [comment]
je savais que le parse xml serais mieux

**Comment by an0Nym0us63** [comment]
allez je close la problématique du vostfr est une autre issue bravo kyah (la meme sur couch lol mais ca je le ferais ;))
nhesites pas a continuer

**Comment by romanocry** [comment]
c'est mis dans quelle branche ? dev ou master du coup ?

**Comment by an0Nym0us63** [comment]
Les deux

---

De: romanocry 
Envoyé: mer., 15/05/2013 22:44
A: mozvip/Sick-Beard Sick-Beard@noreply.github.com
CC: sarakha63 sarakha_ludovic@yahoo.fr
Objet: Re: [Sick-Beard] add gks.gs provider (#26)

**Comment by jgoret** [comment]
Et hop le commit qui permet de dl la VOSTFR si la langue est en anglais ET que les sous titres sont actif dans sickbeard : https://github.com/mozvip/Sick-Beard/pull/95 !

**Comment by romanocry** [comment]
Merci :)
