### ISSUE TITLE
add logo tv channel

### ISSUE THREAD

**Issue by mykado** [mozvip/Sick-Beard#29]
Salut, 

Apparemment, le logo de la chaîne Comédie qui diffusait, et diffusera peut être la saison 3 de, Hero Corp est manquant.

Ceci reste un ajout mineur et non prioritaire bien évidement ;)

Bon courage et merci pour le boulot effectué.

**Comment by an0Nym0us63** [comment]
corrigé un meilleur logo sera trouvé plus tard
