### ISSUE TITLE
Subtitles Renaming

### ISSUE THREAD

**Issue by zaggash** [mozvip/Sick-Beard#30]
Give us the choice to add fr,en or whatever 2 letters or not to the subtitles name.
On some player both name have to be the same.

**Comment by an0Nym0us63** [comment]
if we do so we will be forced to creat two files one without the fr en or whatever and one with so that sickbeard knows what language has been downloaded. This is the only solution. We will provide an option to wheter create the file without the en fr too or not

**Comment by zaggash** [comment]
Ok its a good way to do it.
Otherwise we can change the naming of the show.
But its better if we have the choice ;)

Good job
