### ISSUE TITLE
new parameter in postprocessing/naming

### ISSUE THREAD

**Issue by ghost** [mozvip/Sick-Beard#31]
Avoir la possibilité lors du postprocessing d'ajouter la langue audio dans les paramètres de renommage.
ex : Show Name - S02E03 - Ep Name - FR.ext

**Comment by zaggash** [comment]
C'est déjà faisable en faite :
dans config - postprocessing - naming --> name pattern tu choisis custom et tu peux changer le type de renommage.

Par contre j'ai fais une autre demande qui rejoint la tienne; pouvoir changer le nom des sous titre ;)
Choisir ou pas d'ajouter les deux lettres à la fin du nom du sous titre.

**Comment by an0Nym0us63** [comment]
non car en fait on a pas le pattern audio lang donc a lheure actuelle ce n'est pas faisable pas dynamiquement ou il rajoute EN ou FR en fonction du reglage. Mais on va le rajouter aussi
