### ISSUE TITLE
autoProcessTV.cfg synology install.

### ISSUE THREAD

**Issue by zaggash** [mozvip/Sick-Beard#32]
By default, in the autoProcessTV.cfg, the line "port=8081" is wrong.
The default port configured in sickbeard is 8083.

Regards

**Comment by an0Nym0us63** [comment]
the usual port is 8081 but the sickbeard custom uses 8083 i will make this value editable in the options

**Comment by zaggash** [comment]
Yep, it will be easier for for those not very comfortable with 'vi'
