### ISSUE TITLE
Automatic search doesn't work while manual does

### ISSUE THREAD

**Issue by lodoss5** [mozvip/Sick-Beard#37]
Hi,

First, thanks for this wonderful work, I love it :o)

I configured with only t411 as provider, the manual search works perfectly but the automatic search (I set a frequency of 10min) does not search my file in wanted status.
In logs I only have:
Apr-06 20:24:22 INFO     SEARCHQUEUE-RSS-SEARCH :: No needed episodes found on the RSS feeds
Apr-06 20:24:21 INFO     SEARCHQUEUE-RSS-SEARCH :: Searching all providers for any needed episodes
Apr-06 20:24:21 INFO     SEARCHQUEUE-RSS-SEARCH :: Beginning search for new episodes on RSS
Apr-06 20:24:21 INFO     SEARCHQUEUE-RSS-SEARCH :: Changing all old missing episodes to status WANTED

Thanks for your support

**Comment by an0Nym0us63** [comment]
this is not a bug RSS search doesn't exist for T411 provider. The 10 minutes is only for rss searches.

T411 uses backlog wich is once or twice a day

**Comment by an0Nym0us63** [comment]
are you able to use ssh and vi

you can change the backlog search but it wont be less than one day

**Comment by lodoss5** [comment]
ok thanks for your answer :)

**Comment by an0Nym0us63** [comment]
you will see every episodes will be snatched at one time don't worry ;)

But if you use only T411 and you see that the day after episodes are missing tell me.

**Comment by lodoss5** [comment]
Hi,

I am still having issues, since the last few days my backlog didn't get processed. I only had 1 episode which has been snatched automatically. Did the "Force Backlog" button is supposed to search all files of a serie or just some?

**Comment by an0Nym0us63** [comment]
no the force backlog make a full request.

Did you wait and the episodes came later ?

**Comment by lodoss5** [comment]
I wait 2 days and they are still missing

**Comment by an0Nym0us63** [comment]
give me an example

and your providers ?

**Comment by lodoss5** [comment]
do you want to connect to my sickbeard to see?

**Comment by an0Nym0us63** [comment]
why not give me the information by mp on synocommnity

**Comment by lodoss5** [comment]
message sent :)
