### ISSUE TITLE
Only get VOSTFR

### ISSUE THREAD

**Issue by tior47** [mozvip/Sick-Beard#41]
Bonjour 
D'abord super boulot, fait par des frenchies pour des frenchies :)
Ensuite mon besoin: je cherChe a récupérer en priorité les épisodes en vostfr.
J'ai mis le nom de ma série + vostfr dans le custom' search name, les épisodes avec vostfr sont bien trouvés lors de la recherche mais elle ne s'arrête pas la et continue pour au final me prendre un nzb sans correspondre au custom search name mais uniquement au nom de la série avec une meilleure qualité (je suppose car je ne vois pas d'autres critères)
Je ne pense pas avoir vue d'option qui permettrait de régler ce pb.
Sinon de manière plus générale je veux les vostfr car ma vieille freebox v5 ne lit que les .srt et je ne veux pas membeter a chercher les st correpodnant a la mimine, hors il n'est pas possible de préciser le format de srt souhaité. Sur game of thrones j'ai récupéré une majorité de st autres que .srt :(

Serait il possible de faire une évolution afin de faciliter ce genre de recherche? Ou y'a t il déjà moyen de faire cela d'une autre manière?

Pour info, install sur Syno 4.1 niquel et update ce matin via sb Update Now niquel aussi.

**Comment by an0Nym0us63** [comment]
Alors pour info, le custom search name sert uniquement a préciser, un nom de série surtout si il est différent en VO et VF.

Exemple game of thrones, trône de fer etc..... bien que maintenant cela soit fait aussi. Mais cela peut aider TOuch (2011) touch etc...

Pour la vostfr direct je trouve ca dommage sachant qu'on a la vf et la vo avec sous titre ca fait doublon.

Et rajouter VOSTFR ne voudra pas forcemetn dire sous titre incrusté. Cela pourra ausssi ramener un nzb avec le fichier et le sous titre etccc.. et le problème du format de sous titre sera exactment le même.

Donc je suis pas fan car rajouter cela va alourdir le tout et pas sur de tout que cela resolve les soucis, les problématiques resteront les mêmes

**Comment by tior47** [comment]
Ok je comprend pour le vostfr, c'est plus compliqué que ce que je pensais! Après c'est un choix de dl/regarder la vost et la vf, ce n'est pas mon cas.
Par contre filtrer sur le format du srt te semble aussi inutile/lourd ?

**Comment by tior47** [comment]
Peut être plus simplement pour le genre de problématique "vostfr" ou team par exemple ou que sais je, n'existerait il pas un paramètre Required words configurable comme le Ignored word? Il me semble avoir déjà vu ça qqpart.

**Comment by an0Nym0us63** [comment]
Ben ça faut que je vois comment subliminal fonctionne. Et en fonction rajouter une option pour choies les formats voulus c'est envisageable 

Envoyé de mon iPhone

**Comment by an0Nym0us63** [comment]
mais le required words pas sur car la problématique du format de sous titre restera la meme si il n'est pas incrusté.*

Jopterais plus pour l'option forcer un format

**Comment by tior47** [comment]
Oui en plus pour bien faire il faudrait que ce paramètre soit spécifique par série, du coup peut être encore plus compliqué à implémenter..

**Comment by an0Nym0us63** [comment]
nous gerons selon d'une autre facon maintenant.

Si tu es en VO et que tu acceptes les sous titre dans ta config, les vostfr sont acceptés. Mais pas exclusivement
