### ISSUE TITLE
Choose folder for subtitles

### ISSUE THREAD

**Issue by mykado** [mozvip/Sick-Beard#42]
Salut,

En fait dans Subliminal il était possible de définir un répertoire pour l'analyse des épisodes et la recherche de sous titre.

Par exemple je place tous mes épisodes non vu dans un répertoire "A Voir", et je les classes ensuite. Je trouve ça plus simple pour gérer mes épisodes vu et non vu. Bref, du coup avec l'implémentation de Subliminal dans SickBeard je ne retrouve pas l'option me permettant de choisir le répertoire d'analyse.
Serait il possible d'ajouter ce choix dans les paramètres de recherche des sous titres ?

Merci d'avance.

**Comment by an0Nym0us63** [comment]
Non, les sous titres seront auto matiquement gérés avec le repertoire final de sickbeard.

Nous gerons deja le sous repertoire subs, un repertoire centralisé pour les sous titre et le repertoire courant de la video.

Les sous titre seront toujours recuperes par rapport au dossier de destination de la video post processer. Mais rien ne t'empeche d'utiliser subliminal du nas pour repondre a ton besoin.

Bien que je ne pense pas corriger ca car ca serait trop lourd car sickbeard post processe dans un repertoire final et c'est la que le sous titre sera téléchargé . Dans sickbeeard le sous titreest recupéré par rappport a la notion de video/ episodes (BDD) et pas du tout par rapport a un dossier qu'il scanne.

Mais je veux bien que tu me donnes des détails quand meme sur ton fonctionneemnt

**Comment by mykado** [comment]
Ok, en fait je n'utilise pas le post process de Sickbeard c'est pour ça.

En gros j'ai deux répertoires principaux, un pour les séries vues ou archivés, et un pour les épisodes non vus.
C'est ma gestion pour éviter de me perdre et savoir ou j'en suis dans chaque séries. Je déplace manuellement les épisodes que j'ai vu de la parti "Non-Vu" a "Vu".

Sauf que si je me trompe pas la partie sous titre implémenté dans Sickbeard cherche les sous titres dans le répertoire final, ce qui dans mon cas n'est pas utile puisque si je les ai vu les épisodes avait déjà des sous titres =)

J'avais arrêté d'utiliser Subliminal ya un moment car j'avais la moitié des sous titres qui n'étaient pas les bons, mais je voulais retester depuis l'intégration dans Sickbeard.

Après si le choix du répertoire a scanné est trop lourd a mettre en place c'est pas grave je continuerai manuellement ^^

Pour info, les problèmes que javais avec Subliminal c'est que pour une série style "2 Broke Girls" et "New Girl" j'avais systématiquement les sous titres de Gilmore Girls x)

**Comment by an0Nym0us63** [comment]
tu nutilises pas XBMC ou un truc du genre pour gérer tes vus non vus

**Comment by mykado** [comment]
Nop je n'utilise que les navigateurs classique + lecteur qui va bien suivant le support (PC, Dune, Tablette...)

Enfin comme je te dis, actuellement je fais mes recherche a la main (surtout sur addic7ed) donc je peux continuer comme ça.
Après a voir si la demande reviens ou pas. Je pensais que, vu qu'il s'agissait d'une intégration du framework de Subliminal, la modification serait mineure, mais si ce n'est pas le cas tu peux la zapper ;)

**Comment by an0Nym0us63** [comment]
ben c'est une integration du framework subliminal, mais toute l'organisation et les appels au framework se font via sick. Et sick pour lui connait un seul repertoire de stockage série (ou plusieurs) mais je veux dire n'a pas la notion de reprtoire provisoire. 

Mais le passage de non vu a vu tu le fais a la main car sinon tu as une solution

TU peux definir deux chemins cibles pour le scan de tes séries le vu et le non non vus , tu definit en dossier de destionation des dl le non vus. Donc tout ce passera dans le non vu. Mais quand tu deplaceras a la main de vus a non vus avec un rescan ils seront toujours dans sick mais pointeront sur lo'autre répertoire. Donc totalement transparent et ca rpeond aux besoins (jen reparle sur le forum)
