### ISSUE TITLE
pirate bay encoding

### ISSUE THREAD

**Issue by foXaCe** [mozvip/Sick-Beard#44]
Error while searching PirateBay, skipping: Ä

**Comment by an0Nym0us63** [comment]
More information please , backlog, rss search etc...

Pirate bay is Still in beta we Will Check

Envoyé de mon iPhone

**Comment by gdelcroix** [comment]
tried and obtained same kind of bug:
special caracter in the show name (eg: ô from "trône de fer" in the following debug log)

i copy-pasted the debug level log from a backlog forced refresh.
hope you'll find out what is underneath, seems to be that special caracter coding to me... but i'm not programmer, just a kind of enthusiast ;)

avr-09 01:50:23 DEBUG    SEARCHQUEUE-BACKLOG-121361 :: The highest quality of any match is N/A
avr-09 01:50:23 ERROR    SEARCHQUEUE-BACKLOG-121361 :: Error trying to load BinNewz response: 
avr-09 01:50:22 INFO     SEARCHQUEUE-BACKLOG-121361 :: BinNewz : Searching for Le Trône De Fer.S03
avr-09 01:50:22 DEBUG    SEARCHQUEUE-BACKLOG-121361 :: cache.db: SELECT show_name FROM scene_exceptions WHERE tvdb_id = ? with args [121361]
avr-09 01:50:21 DEBUG    SEARCHQUEUE-BACKLOG-121361 :: cache.db: SELECT show_name FROM scene_exceptions WHERE tvdb_id = ? with args [121361]
avr-09 01:50:20 DEBUG    SEARCHQUEUE-BACKLOG-121361 :: nzbX search url: https://nzbx.co/api/sickbeard?completion=100&q=Le.Tr%C3%B4ne.De.Fer.S03%2A&age=1100&limit=250&cat=tv-hd%7Ctv-sd
avr-09 01:50:20 DEBUG    SEARCHQUEUE-BACKLOG-121361 :: cache.db: SELECT show_name FROM scene_exceptions WHERE tvdb_id = ? with args [121361]
avr-09 01:50:20 DEBUG    SEARCHQUEUE-BACKLOG-121361 :: sickbeard.db: SELECT COUNT(DISTINCT season) as numseasons FROM tv_episodes WHERE showid = ? and season != 0 with args [121361]
AA
AAKeyError: u'\xf4'
AA    return ''.join(map(quoter, s))
AA  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 1250, in quote
AA    searchURL = self.proxy._buildURL(self.searchurl %(urllib.quote(search_string)))
AA  File "/githubrep/Sick-Beard/sickbeard/providers/piratebay/__init__.py", line 209, in _doSearch
AA    itemList += self._doSearch(curString, show=show, season=season)
AA  File "/githubrep/Sick-Beard/sickbeard/providers/generic.py", line 307, in findSeasonResults
AA    curResults = curProvider.findSeasonResults(show, season)
AA  File "/githubrep/Sick-Beard/sickbeard/search.py", line 353, in findSeason
avr-09 01:50:20 DEBUG    SEARCHQUEUE-BACKLOG-121361 :: Traceback (most recent call last):
avr-09 01:50:20 ERROR    SEARCHQUEUE-BACKLOG-121361 :: Error while searching PirateBay, skipping: ô
avr-09 01:50:20 DEBUG    SEARCHQUEUE-BACKLOG-121361 :: cache.db: SELECT show_name FROM scene_exceptions WHERE tvdb_id = ? with args [121361]
avr-09 01:50:20 DEBUG    SEARCHQUEUE-BACKLOG-121361 :: cache.db: SELECT show_name FROM scene_exceptions WHERE tvdb_id = ? with args [121361]
avr-09 01:50:20 DEBUG    SEARCHQUEUE-BACKLOG-121361 :: sickbeard.db: SELECT season, episode,  (SELECT COUNT (*) FROM tv_episodes WHERE showid = tve.showid AND season = tve.season AND location != '' AND location = tve.location AND episode != tve.episode) AS share_location  FROM tv_episodes tve WHERE showid = 121361 AND season = 3 ORDER BY season ASC, episode ASC
avr-09 01:50:09 DEBUG    SEARCHQUEUE-BACKLOG-121361 :: NZBS'R'US search url: https://www.nzbsrus.com/api.php?c91=1&searchtext=Le.Tr%C3%B4ne.De.Fer.S03&uid=#######&lang1=1&key=######&c104=1&lang0=1&lang3=1&xml=1&age=1100&c75=1
avr-09 01:50:09 DEBUG    SEARCHQUEUE-BACKLOG-121361 :: cache.db: SELECT show_name FROM scene_exceptions WHERE tvdb_id = ? with args [121361]
avr-09 01:50:09 DEBUG    SEARCHQUEUE-BACKLOG-121361 :: sickbeard.db: SELECT COUNT(DISTINCT season) as numseasons FROM tv_episodes WHERE showid = ? and season != 0 with args [121361]
avr-09 01:50:09 INFO     SEARCHQUEUE-BACKLOG-121361 :: Searching for stuff we need from Le Trône De Fer season 3
avr-09 01:50:07 DEBUG    SEARCHQUEUE-BACKLOG-121361 :: The highest quality of any match is N/A
avr-09 01:50:07 ERROR    SEARCHQUEUE-BACKLOG-121361 :: Error trying to load BinNewz response: 
avr-09 01:50:06 INFO     SEARCHQUEUE-BACKLOG-121361 :: BinNewz : Searching for Le Trône De Fer.S02
avr-09 01:50:06 DEBUG    SEARCHQUEUE-BACKLOG-121361 :: cache.db: SELECT show_name FROM scene_exceptions WHERE tvdb_id = ? with args [121361]
avr-09 01:50:06 DEBUG    SEARCHQUEUE-BACKLOG-121361 :: cache.db: SELECT show_name FROM scene_exceptions WHERE tvdb_id = ? with args [121361]
avr-09 01:50:05 DEBUG    SEARCHQUEUE-BACKLOG-121361 :: nzbX search url: https://nzbx.co/api/sickbeard?completion=100&q=Le.Tr%C3%B4ne.De.Fer.S02%2A&age=1100&limit=250&cat=tv-hd%7Ctv-sd
avr-09 01:50:05 DEBUG    SEARCHQUEUE-BACKLOG-121361 :: cache.db: SELECT show_name FROM scene_exceptions WHERE tvdb_id = ? with args [121361]
avr-09 01:50:05 DEBUG    SEARCHQUEUE-BACKLOG-121361 :: sickbeard.db: SELECT COUNT(DISTINCT season) as numseasons FROM tv_episodes WHERE showid = ? and season != 0 with args [121361]
AA
AAKeyError: u'\xf4'
AA    return ''.join(map(quoter, s))
AA  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 1250, in quote
AA    searchURL = self.proxy._buildURL(self.searchurl %(urllib.quote(search_string)))
AA  File "/githubrep/Sick-Beard/sickbeard/providers/piratebay/__init__.py", line 209, in _doSearch
AA    itemList += self._doSearch(curString, show=show, season=season)
AA  File "/githubrep/Sick-Beard/sickbeard/providers/generic.py", line 307, in findSeasonResults
AA    curResults = curProvider.findSeasonResults(show, season)
AA  File "/githubrep/Sick-Beard/sickbeard/search.py", line 353, in findSeason
avr-09 01:50:05 DEBUG    SEARCHQUEUE-BACKLOG-121361 :: Traceback (most recent call last):
avr-09 01:50:05 ERROR    SEARCHQUEUE-BACKLOG-121361 :: Error while searching PirateBay, skipping: ô
avr-09 01:50:05 DEBUG    SEARCHQUEUE-BACKLOG-121361 :: cache.db: SELECT show_name FROM scene_exceptions WHERE tvdb_id = ? with args [121361]
avr-09 01:50:05 DEBUG    SEARCHQUEUE-BACKLOG-121361 :: sickbeard.db: SELECT season, episode,  (SELECT COUNT (*) FROM tv_episodes WHERE showid = tve.showid AND season = tve.season AND location != '' AND location = tve.location AND episode != tve.episode) AS share_location  FROM tv_episodes tve WHERE showid = 121361 AND season = 2 ORDER BY season ASC, episode ASC
avr-09 01:49:54 DEBUG    SEARCHQUEUE-BACKLOG-121361 :: NZBS'R'US search url: https://www.nzbsrus.com/api.php?c91=1&searchtext=Le.Tr%C3%B4ne.De.Fer.S02&uid=417852&lang1=1&key=178ecd&c104=1&lang0=1&lang3=1&xml=1&age=1100&c75=1
avr-09 01:49:54 DEBUG    SEARCHQUEUE-BACKLOG-121361 :: cache.db: SELECT show_name FROM scene_exceptions WHERE tvdb_id = ? with args [121361]
avr-09 01:49:54 DEBUG    SEARCHQUEUE-BACKLOG-121361 :: sickbeard.db: SELECT COUNT(DISTINCT season) as numseasons FROM tv_episodes WHERE showid = ? and season != 0 with args [121361]
avr-09 01:49:54 INFO     SEARCHQUEUE-BACKLOG-121361 :: Searching for stuff we need from Le Trône De Fer season 2
avr-09 01:49:54 DEBUG    SEARCHQUEUE-BACKLOG-121361 :: The highest quality of any match is N/A
avr-09 01:49:54 ERROR    SEARCHQUEUE-BACKLOG-121361 :: Error trying to load BinNewz response: 
avr-09 01:49:53 INFO     SEARCHQUEUE-BACKLOG-121361 :: BinNewz : Searching for Le Trône De Fer.S01
avr-09 01:49:53 DEBUG    SEARCHQUEUE-BACKLOG-121361 :: cache.db: SELECT show_name FROM scene_exceptions WHERE tvdb_id = ? with args [121361]
avr-09 01:49:51 DEBUG    SEARCHQUEUE-BACKLOG-121361 :: cache.db: SELECT show_name FROM scene_exceptions WHERE tvdb_id = ? with args [121361]
avr-09 01:49:44 DEBUG    SEARCHQUEUE-BACKLOG-121361 :: nzbX search url: https://nzbx.co/api/sickbeard?completion=100&q=Le.Tr%C3%B4ne.De.Fer.S01%2A&age=1100&limit=250&cat=tv-hd%7Ctv-sd
avr-09 01:49:44 DEBUG    SEARCHQUEUE-BACKLOG-121361 :: cache.db: SELECT show_name FROM scene_exceptions WHERE tvdb_id = ? with args [121361]
avr-09 01:49:44 DEBUG    SEARCHQUEUE-BACKLOG-121361 :: sickbeard.db: SELECT COUNT(DISTINCT season) as numseasons FROM tv_episodes WHERE showid = ? and season != 0 with args [121361]
AA
AAKeyError: u'\xf4'
AA    return ''.join(map(quoter, s))
AA  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 1250, in quote
AA    searchURL = self.proxy._buildURL(self.searchurl %(urllib.quote(search_string)))
AA  File "/githubrep/Sick-Beard/sickbeard/providers/piratebay/__init__.py", line 209, in _doSearch
AA    itemList += self._doSearch(curString, show=show, season=season)
AA  File "/githubrep/Sick-Beard/sickbeard/providers/generic.py", line 307, in findSeasonResults
AA    curResults = curProvider.findSeasonResults(show, season)
AA  File "/githubrep/Sick-Beard/sickbeard/search.py", line 353, in findSeason
avr-09 01:49:44 DEBUG    SEARCHQUEUE-BACKLOG-121361 :: Traceback (most recent call last):
avr-09 01:49:44 ERROR    SEARCHQUEUE-BACKLOG-121361 :: Error while searching PirateBay, skipping: ô
avr-09 01:49:44 DEBUG    SEARCHQUEUE-BACKLOG-121361 :: cache.db: SELECT show_name FROM scene_exceptions WHERE tvdb_id = ? with args [121361]
avr-09 01:49:44 DEBUG    SEARCHQUEUE-BACKLOG-121361 :: sickbeard.db: SELECT season, episode,  (SELECT COUNT (_) FROM tv_episodes WHERE showid = tve.showid AND season = tve.season AND location != '' AND location = tve.location AND episode != tve.episode) AS share_location  FROM tv_episodes tve WHERE showid = 121361 AND season = 1 ORDER BY season ASC, episode ASC
avr-09 01:49:40 DEBUG    CP Server Thread-2 :: sickbeard.db: SELECT COUNT(_) FROM tv_episodes WHERE season != 0 and episode != 0 AND (airdate != 1 OR status IN (4,3276804,204,404,104,804,12804,25604,1604,3204,6404,2,3276802,202,402,102,802,12802,25602,1602,3202,6402,9,3276809,209,409,109,809,12809,25609,1609,3209,6409,6)) AND airdate <= 734967 AND status != 7
avr-09 01:49:40 DEBUG    CP Server Thread-2 :: sickbeard.db: SELECT COUNT(_) FROM tv_episodes WHERE status IN (4,3276804,204,404,104,804,12804,25604,1604,3204,6404,6) AND season != 0 and episode != 0 AND airdate <= 734967
avr-09 01:49:34 DEBUG    CP Server Thread-2 :: sickbeard.db: SELECT COUNT(_) FROM tv_episodes WHERE season != 0 and episode != 0 AND (airdate != 1 OR status IN (4,3276804,204,404,104,804,12804,25604,1604,3204,6404,2,3276802,202,402,102,802,12802,25602,1602,3202,6402,9,3276809,209,409,109,809,12809,25609,1609,3209,6409,6)) AND airdate <= 734967 AND status != 7
avr-09 01:49:34 DEBUG    CP Server Thread-2 :: sickbeard.db: SELECT COUNT(_) FROM tv_episodes WHERE status IN (4,3276804,204,404,104,804,12804,25604,1604,3204,6404,6) AND season != 0 and episode != 0 AND airdate <= 734967
avr-09 01:49:33 DEBUG    SEARCHQUEUE-BACKLOG-121361 :: NZBS'R'US search url: https://www.nzbsrus.com/api.php?c91=1&searchtext=Le.Tr%C3%B4ne.De.Fer.S01&uid=######&lang1=1&key=######&c104=1&lang0=1&lang3=1&xml=1&age=1100&c75=1
avr-09 01:49:33 DEBUG    SEARCHQUEUE-BACKLOG-121361 :: cache.db: SELECT show_name FROM scene_exceptions WHERE tvdb_id = ? with args [121361]
avr-09 01:49:33 DEBUG    SEARCHQUEUE-BACKLOG-121361 :: sickbeard.db: SELECT COUNT(DISTINCT season) as numseasons FROM tv_episodes WHERE showid = ? and season != 0 with args [121361]
avr-09 01:49:33 INFO     SEARCHQUEUE-BACKLOG-121361 :: Searching for stuff we need from Le Trône De Fer season 1
avr-09 01:49:30 DEBUG    CP Server Thread-2 :: sickbeard.db: SELECT COUNT(_) FROM tv_episodes WHERE season != 0 and episode != 0 AND (airdate != 1 OR status IN (4,3276804,204,404,104,804,12804,25604,1604,3204,6404,2,3276802,202,402,102,802,12802,25602,1602,3202,6402,9,3276809,209,409,109,809,12809,25609,1609,3209,6409,6)) AND airdate <= 734967 AND status != 7
avr-09 01:49:30 DEBUG    CP Server Thread-2 :: sickbeard.db: SELECT COUNT(_) FROM tv_episodes WHERE status IN (4,3276804,204,404,104,804,12804,25604,1604,3204,6404,6) AND season != 0 and episode != 0 AND airdate <= 734967
avr-09 01:49:30 DEBUG    CP Server Thread-2 :: sickbeard.db: SELECT \* FROM tv_episodes WHERE showid = ? ORDER BY season DESC, episode DESC with args [82283]
avr-09 01:49:30 DEBUG    CP Server Thread-2 :: sickbeard.db: SELECT \* FROM tv_episodes WHERE showid = ? ORDER BY season DESC, episode DESC with args [248935]
avr-09 01:49:30 DEBUG    CP Server Thread-2 :: sickbeard.db: SELECT \* FROM tv_episodes WHERE showid = ? ORDER BY season DESC, episode DESC with args [80379]
avr-09 01:49:30 DEBUG    CP Server Thread-2 :: sickbeard.db: SELECT \* FROM tv_episodes WHERE showid = ? ORDER BY season DESC, episode DESC with args [164091]
avr-09 01:49:30 DEBUG    CP Server Thread-2 :: sickbeard.db: SELECT \* FROM tv_episodes WHERE showid = ? ORDER BY season DESC, episode DESC with args [185851]
avr-09 01:49:30 DEBUG    CP Server Thread-2 :: sickbeard.db: SELECT \* FROM tv_episodes WHERE showid = ? ORDER BY season DESC, episode DESC with args [121361]
avr-09 01:49:30 DEBUG    CP Server Thread-2 :: sickbeard.db: SELECT \* FROM tv_episodes WHERE showid = ? ORDER BY season DESC, episode DESC with args [82066]
avr-09 01:49:30 DEBUG    CP Server Thread-2 :: sickbeard.db: SELECT \* FROM tv_episodes WHERE showid = ? ORDER BY season DESC, episode DESC with args [95771]
avr-09 01:49:30 DEBUG    CP Server Thread-2 :: sickbeard.db: SELECT \* FROM tv_episodes WHERE showid = ? ORDER BY season DESC, episode DESC with args [79349]
avr-09 01:49:30 DEBUG    CP Server Thread-2 :: sickbeard.db: SELECT \* FROM tv_episodes WHERE showid = ? ORDER BY season DESC, episode DESC with args [258171]
avr-09 01:49:30 DEBUG    CP Server Thread-2 :: sickbeard.db: SELECT \* FROM tv_episodes WHERE showid = ? ORDER BY season DESC, episode DESC with args [80348]
avr-09 01:49:30 DEBUG    CP Server Thread-2 :: sickbeard.db: SELECT \* FROM tv_episodes WHERE showid = ? ORDER BY season DESC, episode DESC with args [219341]
avr-09 01:49:30 DEBUG    CP Server Thread-2 :: sickbeard.db: SELECT status FROM tv_episodes WHERE showid = ? AND season = ? with args [121361, 3]
avr-09 01:49:30 INFO     CP Server Thread-2 :: Seeing if we need any episodes from Le Trône De Fer season 3
avr-09 01:49:30 DEBUG    CP Server Thread-2 :: sickbeard.db: SELECT status FROM tv_episodes WHERE showid = ? AND season = ? with args [121361, 2]
avr-09 01:49:30 INFO     CP Server Thread-2 :: Seeing if we need any episodes from Le Trône De Fer season 2
avr-09 01:49:30 DEBUG    CP Server Thread-2 :: sickbeard.db: SELECT status FROM tv_episodes WHERE showid = ? AND season = ? with args [121361, 1]
avr-09 01:49:30 INFO     CP Server Thread-2 :: Seeing if we need any episodes from Le Trône De Fer season 1
avr-09 01:49:30 DEBUG    CP Server Thread-2 :: sickbeard.db: SELECT DISTINCT(season) as season FROM tv_episodes WHERE showid = ? AND season > 0 and airdate > ? with args [121361, 1]
avr-09 01:49:30 DEBUG    CP Server Thread-2 :: Air-by-date segments: []
avr-09 01:49:30 DEBUG    CP Server Thread-2 :: sickbeard.db: SELECT \* FROM info
avr-09 01:49:30 DEBUG    CP Server Thread-2 :: Retrieving the last check time from the DB
avr-09 01:49:25 DEBUG    CP Server Thread-2 :: sickbeard.db: SELECT COUNT(_) FROM tv_episodes WHERE season != 0 and episode != 0 AND (airdate != 1 OR status IN (4,3276804,204,404,104,804,12804,25604,1604,3204,6404,2,3276802,202,402,102,802,12802,25602,1602,3202,6402,9,3276809,209,409,109,809,12809,25609,1609,3209,6409,6)) AND airdate <= 734967 AND status != 7
avr-09 01:49:25 DEBUG    CP Server Thread-2 :: sickbeard.db: SELECT COUNT(_) FROM tv_episodes WHERE status IN (4,3276804,204,404,104,804,12804,25604,1604,3204,6404,6) AND season != 0 and episode != 0 AND airdate <= 734967
avr-09 01:49:25 DEBUG    CP Server Thread-2 :: sickbeard.db: SELECT \* FROM tv_episodes WHERE showid = ? ORDER BY season DESC, episode DESC with args [82283]
avr-09 01:49:25 DEBUG    CP Server Thread-2 :: sickbeard.db: SELECT \* FROM tv_episodes WHERE showid = ? ORDER BY season DESC, episode DESC with args [248935]
avr-09 01:49:25 DEBUG    CP Server Thread-2 :: sickbeard.db: SELECT \* FROM tv_episodes WHERE showid = ? ORDER BY season DESC, episode DESC with args [80379]
avr-09 01:49:25 DEBUG    CP Server Thread-2 :: sickbeard.db: SELECT \* FROM tv_episodes WHERE showid = ? ORDER BY season DESC, episode DESC with args [164091]
avr-09 01:49:25 DEBUG    CP Server Thread-2 :: sickbeard.db: SELECT \* FROM tv_episodes WHERE showid = ? ORDER BY season DESC, episode DESC with args [185851]
avr-09 01:49:25 DEBUG    CP Server Thread-2 :: sickbeard.db: SELECT \* FROM tv_episodes WHERE showid = ? ORDER BY season DESC, episode DESC with args [121361]
avr-09 01:49:25 DEBUG    CP Server Thread-2 :: sickbeard.db: SELECT \* FROM tv_episodes WHERE showid = ? ORDER BY season DESC, episode DESC with args [82066]
avr-09 01:49:25 DEBUG    CP Server Thread-2 :: sickbeard.db: SELECT \* FROM tv_episodes WHERE showid = ? ORDER BY season DESC, episode DESC with args [95771]
avr-09 01:49:25 DEBUG    CP Server Thread-2 :: sickbeard.db: SELECT \* FROM tv_episodes WHERE showid = ? ORDER BY season DESC, episode DESC with args [79349]
avr-09 01:49:25 DEBUG    CP Server Thread-2 :: sickbeard.db: SELECT \* FROM tv_episodes WHERE showid = ? ORDER BY season DESC, episode DESC with args [258171]
avr-09 01:49:25 DEBUG    CP Server Thread-2 :: sickbeard.db: SELECT \* FROM tv_episodes WHERE showid = ? ORDER BY season DESC, episode DESC with args [80348]
avr-09 01:49:25 DEBUG    CP Server Thread-2 :: sickbeard.db: SELECT \* FROM tv_episodes WHERE showid = ? ORDER BY season DESC, episode DESC with args [219341]
avr-09 01:49:21 DEBUG    CP Server Thread-2 :: sickbeard.db: SELECT COUNT(_) FROM tv_episodes WHERE season != 0 and episode != 0 AND (airdate != 1 OR status IN (4,3276804,204,404,104,804,12804,25604,1604,3204,6404,2,3276802,202,402,102,802,12802,25602,1602,3202,6402,9,3276809,209,409,109,809,12809,25609,1609,3209,6409,6)) AND airdate <= 734967 AND status != 7
avr-09 01:49:21 DEBUG    CP Server Thread-2 :: sickbeard.db: SELECT COUNT(_) FROM tv_episodes WHERE status IN (4,3276804,204,404,104,804,12804,25604,1604,3204,6404,6) AND season != 0 and episode != 0 AND airdate <= 734967
avr-09 01:48:52 DEBUG    CP Server Thread-2 :: sickbeard.db: SELECT COUNT(_) FROM tv_episodes WHERE season != 0 and episode != 0 AND (airdate != 1 OR status IN (4,3276804,204,404,104,804,12804,25604,1604,3204,6404,2,3276802,202,402,102,802,12802,25602,1602,3202,6402,9,3276809,209,409,109,809,12809,25609,1609,3209,6409,6)) AND airdate <= 734967 AND status != 7
avr-09 01:48:52 DEBUG    CP Server Thread-2 :: sickbeard.db: SELECT COUNT(_) FROM tv_episodes WHERE status IN (4,3276804,204,404,104,804,12804,25604,1604,3204,6404,6) AND season != 0 and episode != 0 AND airdate <= 734967
avr-09 01:48:49 DEBUG    CP Server Thread-2 :: sickbeard.db: SELECT COUNT(_) FROM tv_episodes WHERE season != 0 and episode != 0 AND (airdate != 1 OR status IN (4,3276804,204,404,104,804,12804,25604,1604,3204,6404,2,3276802,202,402,102,802,12802,25602,1602,3202,6402,9,3276809,209,409,109,809,12809,25609,1609,3209,6409,6)) AND airdate <= 734967 AND status != 7
avr-09 01:48:49 DEBUG    CP Server Thread-2 :: sickbeard.db: SELECT COUNT(_) FROM tv_episodes WHERE status IN (4,3276804,204,404,104,804,12804,25604,1604,3204,6404,6) AND season != 0 and episode != 0 AND airdate <= 734967
avr-09 01:48:47 DEBUG    CP Server Thread-2 :: sickbeard.db: SELECT COUNT(_) FROM tv_episodes WHERE season != 0 and episode != 0 AND (airdate != 1 OR status IN (4,3276804,204,404,104,804,12804,25604,1604,3204,6404,2,3276802,202,402,102,802,12802,25602,1602,3202,6402,9,3276809,209,409,109,809,12809,25609,1609,3209,6409,6)) AND airdate <= 734967 AND status != 7
avr-09 01:48:47 DEBUG    CP Server Thread-2 :: sickbeard.db: SELECT COUNT(_) FROM tv_episodes WHERE status IN (4,3276804,204,404,104,804,12804,25604,1604,3204,6404,6) AND season != 0 and episode != 0 AND airdate <= 734967
avr-09 01:48:36 DEBUG    CP Server Thread-2 :: sickbeard.db: SELECT COUNT(_) FROM tv_episodes WHERE season != 0 and episode != 0 AND (airdate != 1 OR status IN (4,3276804,204,404,104,804,12804,25604,1604,3204,6404,2,3276802,202,402,102,802,12802,25602,1602,3202,6402,9,3276809,209,409,109,809,12809,25609,1609,3209,6409,6)) AND airdate <= 734967 AND status != 7
avr-09 01:48:36 DEBUG    CP Server Thread-2 :: sickbeard.db: SELECT COUNT(_) FROM tv_episodes WHERE status IN (4,3276804,204,404,104,804,12804,25604,1604,3204,6404,6) AND season != 0 and episode != 0 AND airdate <= 734967
avr-09 01:48:28 DEBUG    CP Server Thread-2 :: sickbeard.db: SELECT COUNT(_) FROM tv_episodes WHERE season != 0 and episode != 0 AND (airdate != 1 OR status IN (4,3276804,204,404,104,804,12804,25604,1604,3204,6404,2,3276802,202,402,102,802,12802,25602,1602,3202,6402,9,3276809,209,409,109,809,12809,25609,1609,3209,6409,6)) AND airdate <= 734967 AND status != 7
avr-09 01:48:28 DEBUG    CP Server Thread-2 :: sickbeard.db: SELECT COUNT(_) FROM tv_episodes WHERE status IN (4,3276804,204,404,104,804,12804,25604,1604,3204,6404,6) AND season != 0 and episode != 0 AND airdate <= 734967
avr-09 01:48:25 DEBUG    CP Server Thread-2 :: sickbeard.db: SELECT COUNT(_) FROM tv_episodes WHERE season != 0 and episode != 0 AND (airdate != 1 OR status IN (4,3276804,204,404,104,804,12804,25604,1604,3204,6404,2,3276802,202,402,102,802,12802,25602,1602,3202,6402,9,3276809,209,409,109,809,12809,25609,1609,3209,6409,6)) AND airdate <= 734967 AND status != 7
avr-09 01:48:25 DEBUG    CP Server Thread-2 :: sickbeard.db: SELECT COUNT(*) FROM tv_episodes WHERE status IN (4,3276804,204,404,104,804,12804,25604,1604,3204,6404,6) AND season != 0 and episode != 0 AND airdate <= 734967

**Comment by gdelcroix** [comment]
pirate bay uses HTML entities on their site but the searchbox nor the rss are accented characters friendly, as for  nzbsrus and nzbx in my debug and on their search modules uses encodeURI/decodeURI but seems to have no suitable results with manual search neither :(

**Comment by an0Nym0us63** [comment]
could you test last commit and reply thanks

**Comment by gdelcroix** [comment]
j'aurais tendance à dire pas mieux avec utf-8 forcé dans l'encode ? 

avr-10 00:18:03 DEBUG    SEARCHQUEUE-BACKLOG-121361 :: The highest quality of any match is N/A
avr-10 00:18:03 ERROR    SEARCHQUEUE-BACKLOG-121361 :: Error trying to load BinNewz response: 
avr-10 00:18:03 INFO     SEARCHQUEUE-BACKLOG-121361 :: BinNewz : Searching for Le Trône De Fer.S03
avr-10 00:18:03 DEBUG    SEARCHQUEUE-BACKLOG-121361 :: cache.db: SELECT show_name FROM scene_exceptions WHERE tvdb_id = ? with args [121361]
avr-10 00:18:02 DEBUG    SEARCHQUEUE-BACKLOG-121361 :: cache.db: SELECT show_name FROM scene_exceptions WHERE tvdb_id = ? with args [121361]
avr-10 00:18:01 DEBUG    SEARCHQUEUE-BACKLOG-121361 :: nzbX search url: https://nzbx.co/api/sickbeard?completion=100&q=Le.Tr%C3%B4ne.De.Fer.S03%2A&age=1100&limit=250&cat=tv-hd%7Ctv-sd
avr-10 00:18:01 DEBUG    SEARCHQUEUE-BACKLOG-121361 :: cache.db: SELECT show_name FROM scene_exceptions WHERE tvdb_id = ? with args [121361]
avr-10 00:18:01 DEBUG    SEARCHQUEUE-BACKLOG-121361 :: sickbeard.db: SELECT COUNT(DISTINCT season) as numseasons FROM tv_episodes WHERE showid = ? and season != 0 with args [121361]
avr-10 00:18:01 DEBUG    SEARCHQUEUE-BACKLOG-121361 :: Search string: http://thepiratebay.se/search/Le.Tr%C3%B4ne.De.Fer%20S03E02%7C3x02%7C03x02/0/7/200
avr-10 00:18:00 DEBUG    SEARCHQUEUE-BACKLOG-121361 :: Search string: http://thepiratebay.se/search/Le.Tr%C3%B4ne.De.Fer%20S03E01%7C3x01%7C03x01/0/7/200
avr-10 00:18:00 DEBUG    SEARCHQUEUE-BACKLOG-121361 :: cache.db: SELECT show_name FROM scene_exceptions WHERE tvdb_id = ? with args [121361]
avr-10 00:18:00 DEBUG    SEARCHQUEUE-BACKLOG-121361 :: cache.db: SELECT show_name FROM scene_exceptions WHERE tvdb_id = ? with args [121361]
avr-10 00:18:00 DEBUG    SEARCHQUEUE-BACKLOG-121361 :: sickbeard.db: SELECT season, episode,  (SELECT COUNT (*) FROM tv_episodes WHERE showid = tve.showid AND season = tve.season AND location != '' AND location = tve.location AND episode != tve.episode) AS share_location  FROM tv_episodes tve WHERE showid = 121361 AND season = 3 ORDER BY season ASC, episode ASC
avr-10 00:17:55 DEBUG    SEARCHQUEUE-BACKLOG-121361 :: NZBS'R'US search url: https://www.nzbsrus.com/api.php?c91=1&searchtext=Le.Tr%C3%B4ne.De.Fer.S03&uid=UIDUID&lang1=1&key=KEYKEY&c104=1&lang0=1&lang3=1&xml=1&age=1100&c75=1
avr-10 00:17:55 DEBUG    SEARCHQUEUE-BACKLOG-121361 :: cache.db: SELECT show_name FROM scene_exceptions WHERE tvdb_id = ? with args [121361]
avr-10 00:17:55 DEBUG    SEARCHQUEUE-BACKLOG-121361 :: sickbeard.db: SELECT COUNT(DISTINCT season) as numseasons FROM tv_episodes WHERE showid = ? and season != 0 with args [121361]
avr-10 00:17:55 INFO     SEARCHQUEUE-BACKLOG-121361 :: Searching for stuff we need from Le Trône De Fer season 3

**Comment by an0Nym0us63** [comment]
Bon a retenter, j'ai pas pu tester sur le nas avant car j'avais le volume en reconstruction et sur windows ça passe. Mais j'ai une piste

Envoyé de mon iPhone

**Comment by gdelcroix** [comment]
j'ai mis que le level error pas le level debug... un peu endormi le greg ce soir !
je remets le bon log en edit de mon précédent post dans la minute (ou deux)

**Comment by an0Nym0us63** [comment]
Pas de soucis isole la partie intéressante. Moi d'ailleurs dodo

Envoyé de mon iPhone

**Comment by gdelcroix** [comment]
done, g'nite ;)

**Comment by an0Nym0us63** [comment]
Met un custom search name: game of thrones

Il te les trouvera.

Mais ça résoud pas le soucis

Mais dans tous les cas pour le trône de fer il faut mettre le custom search name avec le nom anglais. Car toutes les releases même française sont avec game of thrones

Envoyé de mon iPhone

**Comment by gdelcroix** [comment]
mais VA TE COUCHER BORDEL ! Mdr

**Comment by an0Nym0us63** [comment]
Oui j'y go. Mais fais le test ça te les récupérera ;)

Envoyé de mon iPhone

**Comment by gdelcroix** [comment]
ça marche avec le custom search, par contre il ne valide pas les "multi" comme contenant du français... wtf ?

**Comment by gdelcroix** [comment]
avr-11 01:22:33 INFO     SEARCHQUEUE-BACKLOG-121361 :: Ignoring result Game.Of.Thrones.S01DVD1.PAL.MULTI.DVDR-VIAZAC because the language: english does not match the desired language: french

et quid de la tolérance (ou pas ) des résultats vostfr ? 
exemple :
avr-11 01:21:33 INFO     SEARCHQUEUE-BACKLOG-82066 :: Ignoring result Fringe.S05E08.VOSTFR.Gillop.avi because the language: english does not match the desired language: french

je sais, je suis chiant... ;)

mais je peux compenser avec la fourniture d'un bout de code que j'avais pondu il y a quelques mois et qui marchait pas mal à l'époque pour ajouter le RSS de binsearch.net dans les providers :+1:

**Comment by an0Nym0us63** [comment]
Ça c normal on a pas gère les langues , pirate bay est en beta

Envoyé de mon iPhone
