### ISSUE TITLE
bug sur le dernier update

### ISSUE THREAD

**Issue by gdelcroix** [mozvip/Sick-Beard#48]
Bonjour,
apres mise a jour sur le dernier commit, impossible d'afficher les pages de configuration. Une erreur sur le module subtitles provoque un plantage de cherrypy.

une remontée sur la dernière modification apportée à postprocessor.py rend à nouveau les menus fonctionnels.

**Comment by an0Nym0us63** [comment]
Peux tu me donner exactement ce que tu fais sur quoi tu cliques jusqu'à arriver a l'écran d'erreur stp.

Envoyé de mon iPhone

**Comment by an0Nym0us63** [comment]
Car moi jaccedes a tout les écrans. Donc donne moi les éléments pour reproduire et aussi l'erreur exact avec le trace back stp

Envoyé de mon iPhone

**Comment by gdelcroix** [comment]
faux positif... à n'y rien comprendre... j'avais cloné le git pour avoir quelque chose de propre, et donc là impossible d'obtenir les pages de configuration, erreur systématique concernant postprocessor.py....
comme j'etais remonté d'un commit pour que ça fonctionne, je me suis dit que pour reproduire le bug, j'allais refaire la même chose: maintenant ça marche ! je vais me pendre et je reviens...

**Comment by an0Nym0us63** [comment]
Lol

Avant de te pendre close l'issue lol. 

Probablement un mauvais clone ou un fichier corrompu ou un mauvais droit.

Après si ça se reproduit nhesites pas

Envoyé de mon iPhone

**Comment by gdelcroix** [comment]
oki je close ;)
