### ISSUE TITLE
T411.py petites erreurs

### ISSUE THREAD

**Issue by arpheus** [mozvip/Sick-Beard#54]
Bonjour,

J'ai noté quelques erreurs dans mon fichier t411.py qui m’empêchaient de chercher correctement des fichiers.
Ligne 122 : downloadTorrentLink = torrentSoup.find("a", text="uT�l�charger")
Ligne 103 : logger.log(u"Search string: " + searchUrl, logger.DEBUG)

Corrigés en : 
-downloadTorrentLink = torrentSoup.find("a", text="Télécharger")
-logger.log("Search string: " + searchUrl, logger.DEBUG)

Qui ont résolus mon problème.
Ne sachant pas si je suis le seul concerné, je préfère le signaler :)

Merci pour votre super boulot.

**Comment by an0Nym0us63** [comment]
Euh tu es sur quel plateforme et tu as recup comment le fork . Car ça vient pas de nous sûrement un changement au moment d'une copie

Peux tu nous en dire plus

Envoyé de mon iPhone

**Comment by an0Nym0us63** [comment]
as non t as raison il ya eu un soucis sur un de nos dernier commit

alors la je suis surpris

bien vue

**Comment by an0Nym0us63** [comment]
fixed

https://github.com/mozvip/Sick-Beard/blob/development/sickbeard/providers/t411.py

**Comment by arpheus** [comment]
super ;)
