### ISSUE TITLE
Rétention non prise en compte

### ISSUE THREAD

**Issue by FunFR** [mozvip/Sick-Beard#57]
Bien que la rétention soit configurée à 40 jours dans les "Search settings", sick continue d'envoyer à SABnzbd des épisodes qui sont plus anciens (240j, 568j, ...).

Ce problème est apparu depuis que je suis passé de la release officielle (package synology) à votre fork (package sick custom).

Les requêtes des providers semblent pourtant bien prendre en compte la retention d'après les logs : 
Ex:  
Search url: http://lolo.sickbeard.com/api?limit=100&t=tvsearch&season=8&rid=6554&maxage=40&cat=5030%2C5040
nzbX search url: https://nzbx.co/api/sickbeard?completion=100&q=Weeds.S08%2A&age=40&limit=250&cat=tv-hd%7Ctv-sd

Tous les "Search url: de ma log semblent intégrer ma rétention correctement

**Comment by an0Nym0us63** [comment]
peux tu nous dire de quel provider vient les fichiers dépassant la rétention

Binnews non ?

Si c'est le cas je pense avoir une idée

**Comment by FunFR** [comment]
Effectivement j'ai retrouvé tous les nzb dans les flux BinnewZ.
Par contre, je n'ai pas trouvé les url de binnewz dans la log.

En tout cas tant mieux si tu as une idée.

**Comment by FunFR** [comment]
Des news @sarakha63 ?

**Comment by an0Nym0us63** [comment]
je vais m'y pencher maintenant que le rest est un peu plus trnaquille
