### ISSUE TITLE
base de travail pour l'ajout d'un autre provider

### ISSUE THREAD

**Issue by gdelcroix** [mozvip/Sick-Beard#60]
j'avais fait ça sur une version plus ancienne de sickbeard, il y aura certainement des modifications a refaire pour que ça fonctionne avec les derniers commits, mais la base est là...
https://code.google.com/p/sickbeard-binsearch/source/browse/

de mémoire j'ai moddé du code
dans data/interface/default/config_providers.tmpl
dans sickbeard/init.py
et bien sur dans providers ;)

a voir, j'avais pas eu besoin de gérer quoi que ce soit vis à vis de la database, mais je ne sais pas si ce ne serait pas nécessaire...

**Comment by an0Nym0us63** [comment]
binsearch est maintenant indirectement implémenté via binnews
