### ISSUE TITLE
Add chanel icon

### ISSUE THREAD

**Issue by narfight** [mozvip/Sick-Beard#63]
Bonjour tout le monde,

Voici 3 logo qui manque dans mon Sickbeard :
MTV Network : http://fr.wikipedia.org/wiki/MTV_Networks
Netfix : http://fr.wikipedia.org/wiki/Netflix
Fuji_TV : https://fr.wikipedia.org/wiki/Fuji_Television

Bien à vous,
Narfight

**Comment by an0Nym0us63** [comment]
pourrais tu me donner les séries ratachés à ces logo que je puisse tester l'affichage merci ;)

**Comment by narfight** [comment]
MTV Network : Fur TV (http://thetvdb.com/?tab=series&id=83128)
Netfix : Doctor Horrible's Sing-Along Blog (http://thetvdb.com/?tab=series&id=82507)
Fuji_TV : GTO (http://thetvdb.com/?tab=series&id=79071)

Et depuis, j'ai aussi ceci à ajouter la la liste de mes demandes :-)
Syndicated : La Panthère rose (http://thetvdb.com/?tab=series&id=71554)
TVA (https://en.wikipedia.org/wiki/TVA_(Canada) ) : Le coeur a ses raisons (http://thetvdb.com/?tab=series&id=80741)

Merci d'avance à toi

**Comment by an0Nym0us63** [comment]
fixed
