### ISSUE TITLE
Crash récurrente de l'application pendant la recherche d'épisodes

### ISSUE THREAD

**Issue by narfight** [mozvip/Sick-Beard#64]
Bonjour,

J'ai constaté que mon programme plantais +/- tout les jours et je devais donc le relancer dans l'interface du synology. Mais maintenant, Sickbeard plante toutes les 10 minutes et cela devient vraiment gênant !

Voici les log des 3 derniers crache de ce matin :

> Apr-14 09:47:25 INFO     SEARCHQUEUE-BACKLOG-73141 :: Searching for download : _**, search string = *__.S07E03.FRENCH.LD.HDTV.XViD-EPZ on BinSearch
> Apr-14 09:47:36 INFO     SEARCHQUEUE-BACKLOG-73141 :: Searching for download : *_\* - ĂŠpisodes 1 Ă  7 - 9 Ă  13 - 15 Ă  19 , search string = _**.s06e_\* on NZBIndex
> Apr-14 09:47:46 INFO     SEARCHQUEUE-BACKLOG-73141 :: Searching for download : **\* - ĂŠpisodes 1 Ă  7 - 9 Ă  13 - 15 Ă  19 , search string = _**.s06e_\* on NZBClub
> Apr-14 09:48:12 ERROR    SEARCHQUEUE-BACKLOG-73141 :: Searching from NZBClub failed : utf8
> Apr-14 09:48:12 INFO     SEARCHQUEUE-BACKLOG-73141 :: Searching for download : **\* Saison 6 - ĂŠpisodes 1 Ă  7 - 9 Ă  13 - 15 Ă  19 , search string = epz-_**.s06e_\* on BinSearch
> Apr-14 09:48:33 INFO     SEARCHQUEUE-BACKLOG-73141 :: BinNewz : Searching for _**.S09
> Apr-14 09:48:46 INFO     SEARCHQUEUE-BACKLOG-73141 :: Searching for download : *_\* S07e03 , search string = _**.S07E03.FRENCH.LD.HDTV.XViD-EPZ on NZBIndex
> Apr-14 09:48:56 INFO     SEARCHQUEUE-BACKLOG-73141 :: Searching for download : *_\* S07e03 , search string = ***.S07E03.FRENCH.LD.HDTV.XViD-EPZ on NZBClub

**Crach suivant**

> Apr-14 09:40:24 INFO     SEARCHQUEUE-BACKLOG-73141 :: Searching for stuff we need from **\* season 9
> Apr-14 09:40:24 DEBUG    SEARCHQUEUE-BACKLOG-73141 :: cache.db: SELECT show_name FROM scene_exceptions WHERE tvdb_id = ? with args [73141]
> Apr-14 09:40:24 INFO     SEARCHQUEUE-BACKLOG-73141 :: BinNewz : Searching for **_.S09
> Apr-14 09:40:29 DEBUG    CP Server Thread-5 :: sickbeard.db: SELECT COUNT(_) FROM tv_episodes WHERE status IN (4,3276804,204,404,104,804,12804,25604,1604,3204,6404,6) AND season != 0 and episode != 0 AND airdate <= 734972
> Apr-14 09:40:29 DEBUG    CP Server Thread-5 :: sickbeard.db: SELECT COUNT(_) FROM tv_episodes WHERE season != 0 and episode != 0 AND (airdate != 1 OR status IN (4,3276804,204,404,104,804,12804,25604,1604,3204,6404,2,3276802,202,402,102,802,12802,25602,1602,3202,6402,9,3276809,209,409,109,809,12809,25609,1609,3209,6409,6)) AND airdate <= 734972 AND status != 7
> Apr-14 09:40:37 INFO     SEARCHQUEUE-BACKLOG-73141 :: Searching for download : *_\* S07e03 , search string = _**.S07E03.FRENCH.LD.HDTV.XViD-EPZ on NZBIndex
> Apr-14 09:40:38 INFO     SEARCHQUEUE-BACKLOG-73141 :: Searching for download : *_\* S07e03 , search string = ***.S07E03.FRENCH.LD.HDTV.XViD-EPZ on NZBClub

**Crach suivant**

> Apr-14 07:59:38 INFO     SEARCHQUEUE-BACKLOG-80337 :: Searching for stuff we need from **\* season 5
> Apr-14 07:59:38 DEBUG    SEARCHQUEUE-BACKLOG-80337 :: cache.db: SELECT show_name FROM scene_exceptions WHERE tvdb_id = ? with args [80337]
> Apr-14 07:59:38 INFO     SEARCHQUEUE-BACKLOG-80337 :: BinNewz : Searching for ***
> Apr-14 07:59:39 INFO     SEARCHQUEUE-BACKLOG-80337 :: Searching for download : **\* S05E01 à 13   (a.b.x et cores), search string = 31294.S05E on NZBIndex
> Apr-14 07:59:51 INFO     SEARCHQUEUE-BACKLOG-80337 :: Found : 31294.S05E on NZBIndex
> Apr-14 07:59:51 INFO     SEARCHQUEUE-BACKLOG-80337 :: Searching for download : **\* S05E011, search string = ***.S05E11.FRENCH.LD.DVDRiP.XViD-EPZ on NZBIndex

Les 1er crach étaient sur la même série alors que le dernier était sur une autre.

Je ne sais pas trop quoi donner plus comme info en plus pour diagnostiquer le problème. Je suis sur la dernière version du DSM sur un DS1511+ et le Sickbeard est au dernier commit dispo.

Merci d'avance pour l'aide !
Narfight

**Comment by an0Nym0us63** [comment]
Il n'y a rien dans la log expliquant ou montrant le krach. Il faudrait voir sur le forum avec le créateur du spk. Mais il me semble que quelqu'un a déjà eu le soucis et cela venait de l'utilisation d'une autre appli qui faisait conflit. Cela ne vient pas de sickbeard. Au pire redémarre le nas

Envoyé de mon iPhone

**Comment by narfight** [comment]
Je viens de réussir à stabiliser l'application en désactivant le provider BinnewZ ! Je me demande si il n'aurait pas un bug avec les caractères non alpha-numérique dans le titre de la série ou de l'épisode.

**Comment by an0Nym0us63** [comment]
Non il y'a un bug utf8 connu sur nzbclub. Mais celui la n'a pas de consequence et chez moi lappli ne plante pas. Mais peut être que tu as mis le doigt sur quelque chose qui pourrait faire cracher lappli pour des systèmes sensibles

Envoyé de mon iPhone

**Comment by narfight** [comment]
SB à tourné 3h sans problème sans BinnewZ. Je reboot le syno, réactive le provider et relancer SB : Crach systématique dans les 3 minutes

> Apr-14 12:53:39 INFO     SEARCHQUEUE-BACKLOG-73141 :: BinNewz : Searching for SERIE!.S09
> Apr-14 12:53:58 INFO     SEARCHQUEUE-BACKLOG-73141 :: Searching for download : SERIE ! S07e03 , search string = SERIE.S07E03.FRENCH.LD.HDTV.XViD-EPZ on NZBIndex
> Apr-14 12:54:06 INFO     SEARCHQUEUE-BACKLOG-73141 :: Searching for download : SERIE ! S07e03 , search string = SERIE.S07E03.FRENCH.LD.HDTV.XViD-EPZ on NZBClub

Dans le nom de la série, il a un !. Es-tu certain que cela ne pose pas de souci ?

**Comment by an0Nym0us63** [comment]
Ca peux poser problème mais pas de la à faire crasher l'application. Je testerais 

Envoyé depuis un mobile Samsung

-------- Message d'origine --------
De : narfight notifications@github.com 
Date :  
A : mozvip/Sick-Beard Sick-Beard@noreply.github.com 
Cc : sarakha63 sarakha_ludovic@yahoo.fr 
Objet : Re: [Sick-Beard] Crash récurrente de l'application pendant la recherche d'épisodes (#64) 

SB à tourné 3h sans problème sans BinnewZ. Je reboot le syno, réactive le provider et relancer SB : Crach systématique dans les 3 minutes

Apr-14 12:53:39 INFO SEARCHQUEUE-BACKLOG-73141 :: BinNewz : Searching for SERIE!.S09
Apr-14 12:53:58 INFO SEARCHQUEUE-BACKLOG-73141 :: Searching for download : SERIE ! S07e03 , search string = SERIE.S07E03.FRENCH.LD.HDTV.XViD-EPZ on NZBIndex
Apr-14 12:54:06 INFO SEARCHQUEUE-BACKLOG-73141 :: Searching for download : SERIE ! S07e03 , search string = SERIE.S07E03.FRENCH.LD.HDTV.XViD-EPZ on NZBClub

Dans le nom de la série, il a un !. Es-tu certain que cela ne pose pas de souci ?

**Comment by Jahislove** [comment]
J'ai le meme probleme, Sickbeard plante au bout de quelques heures.
je vais desactiver BinNews pour voir

**Comment by Jahislove** [comment]
Je confirme que le probleme semble bien venir de binNews , car la ça fait 48h que je l'ai desactivé et aucun crash

**Comment by narfight** [comment]
As-tu des sérires ou des épisodes avec des carratéres de ponctuation ou autre ?

Chez moi, c'est le ! qui semble cracher le programme

**Comment by an0Nym0us63** [comment]
je suis pas convaincu des caractères spéciaux, chez moi j'ai le trône de fer et l'appli ne crash pas.

Pourrais je avoir les logs de la minute avant le crash

**Comment by an0Nym0us63** [comment]
sinon essayé avec les custom search names de mettre le meme titre sans le !  (juste pour voir)

**Comment by narfight** [comment]
J'ai fait le test sur "American Dad!", custom search définit sur "american dad" et voici le log du crash qui est survenu très rapidement

> Apr-23 17:32:39 INFO     SEARCHQUEUE-BACKLOG-73141 :: Searching for stuff we need from American Dad! season 9
> Apr-23 17:32:39 DEBUG    SEARCHQUEUE-BACKLOG-73141 :: cache.db: SELECT show_name FROM scene_exceptions WHERE tvdb_id = ? with args [73141]
> Apr-23 17:32:39 INFO     SEARCHQUEUE-BACKLOG-73141 :: BinNewz : Searching for American Dad!.S09
> Apr-23 17:32:53 INFO     SEARCHQUEUE-BACKLOG-73141 :: Searching for download : American Dad ! S07e03 , search string = American.Dad.S07E03.FRENCH.LD.HDTV.XViD-EPZ on NZBIndex
> Apr-23 17:32:54 INFO     SEARCHQUEUE-BACKLOG-73141 :: Searching for download : American Dad ! S07e03 , search string = American.Dad.S07E03.FRENCH.LD.HDTV.XViD-EPZ on NZBClub

**Comment by an0Nym0us63** [comment]
Le s eul hic c que je vois aucune erreur dans la log. Mais le fautif est la partie nzbclub de binnews. Si tu sais manipuler vi et le ssh. Pour tester il faudrait enlever nzbclub de la liste au debut du fichier main de binbews

---

De: narfight 
Envoyé: mar., 23/04/2013 17:57
A: mozvip/Sick-Beard Sick-Beard@noreply.github.com
CC: sarakha63 sarakha_ludovic@yahoo.fr
Objet: Re: [Sick-Beard] Crash récurrente de l'application pendant la recherche d'épisodes (#64)

**Comment by narfight** [comment]
Peux-tu me confirmer quel fichier ?
celui-ci ? https://github.com/mozvip/Sick-Beard/blob/development/sickbeard/providers/binnewz/__init__.py

et si oui, quel est la modif exacte ?

**Comment by an0Nym0us63** [comment]
oui celui la il faut enlever NZBCLUB de la ligne 42 et tester voir si tu reproduis comme cela.

Merci

**Comment by narfight** [comment]
Comme cela, le logiciel semble stable !

**Comment by narfight** [comment]
Je confirme, plus aucun plantage avec la suppresion de NZBCLUB

**Comment by an0Nym0us63** [comment]
Ok tu confirmes donc mon hypothèse

---

De: narfight 
Envoyé: lun., 29/04/2013 16:15
A: mozvip/Sick-Beard Sick-Beard@noreply.github.com
CC: sarakha63 sarakha_ludovic@yahoo.fr
Objet: Re: [Sick-Beard] Crash récurrente de l'application pendant la recherche d'épisodes (#64)

**Comment by an0Nym0us63** [comment]
fait dans le nouveau fork
