### ISSUE TITLE
VO/VF ou VE/VF

### ISSUE THREAD

**Issue by Jmi95110** [mozvip/Sick-Beard#67]
Bonjour, je viens de découvrir cette version modifiée, très chouette d'ailleurs, le béret fait la différence, par contre, j'ai un doute... je souhaite ajouter un anime en VO ... Mais, seul le français ou l'anglais est disponible... avez-vous la possibilité comme le nom de l'application l'indique de faire de la VO?

**Comment by an0Nym0us63** [comment]
si tu met anglais cela correspond à VO

**Comment by Jmi95110** [comment]
Bonjour, merci, mais non merci, VO = Version Originale. je prends un example que tout le monde va connaître,'Dragon ball', je ne veux pas la version française, mais la version originale sous titrée, ce serait vraiment top d'avoir l'audio en japonais et de beaux sous titres non incrustés.
