### ISSUE TITLE
Bug with T411 search

### ISSUE THREAD

**Issue by arpheus** [mozvip/Sick-Beard#69]
Je rencontre depuis quelques jours un bug de recherche.

Mes logs SickBeard sont pleins de ce genre d'incohérences : 
SEARCHQUEUE-MANUAL-SEARCH :: Using cached parse result for: XXXXXXX s01e02 HDTV x264-TEAM VO
SEARCHQUEUE-MANUAL-SEARCH :: Checking if we want episode 1x2 at quality SD TV
SEARCHQUEUE-MANUAL-SEARCH :: any,best = [4, 32, 128] [] and we are 1
SEARCHQUEUE-MANUAL-SEARCH :: I know for sure I don't want this episode, saying no
SEARCHQUEUE-MANUAL-SEARCH :: Ignoring result XXXXXXX s01e02 HDTV x264-TEAM VO because we don't want an episode that is SD TV

Ne sachant pas par quel bout commencer pour trouver l'erreur, je me tourne vers vous.

**Comment by an0Nym0us63** [comment]
tu demandes SDTV comme qualité ?

**Comment by arpheus** [comment]
Non, 720p.
Ce qui m'étonne, c'est qu'il considère un épisode  nommé explicitement HDTV comme un SDTV.

**Comment by an0Nym0us63** [comment]
HDTV ce n'est pas du 720p c'est normal qu'ille rejette.

HDTV ca veut dire pris d'une chaine HD et rippé en SD

**Comment by an0Nym0us63** [comment]
apres il le rejette car tu demandes du 720p mais par contre ca n'empèche quil devrait le reconnaitre en HDTV.

Mais meme si il le reconnaissait en HDTV il serait pas pris en demandant du 720p

**Comment by Franck69** [comment]
bonjour,  sarakha63
je profite du fait que tu sois dans le coin pour te poser une question tte bete pour toi certainement, mais qui demeure sans reponse pour moi :)

**Comment by Franck69** [comment]
j'ai telecharge certains episodes a la main, mis dans le dossier de la serie en question, mais Sickbeard ne le reconnait pas, et donc, ne les classes pas...

 Apr-23 20:38:58 INFO     SHOWQUEUE-REFRESH :: No new cache images needed, not retrieving new ones
Apr-23 20:38:58 INFO     SHOWQUEUE-REFRESH :: Checking & filling cache for show Les Experts
Apr-23 20:38:58 INFO     SHOWQUEUE-REFRESH :: 72546: Writing NFOs for all episodes
Apr-23 20:38:58 INFO     SHOWQUEUE-REFRESH :: 72546: Loading all episodes with a location from the database
Apr-23 20:38:58 ERROR    SHOWQUEUE-REFRESH :: Unable to parse the filename /volume1/video/Les Experts/Les experts Las VegasS13E02.avi into a valid episode
Apr-23 20:38:58 ERROR    SHOWQUEUE-REFRESH :: Unable to parse the filename /volume1/video/Les Experts/Les experts Las VegasS13E04.avi into a valid episode
Apr-23 20:38:58 ERROR    SHOWQUEUE-REFRESH :: Unable to parse the filename /volume1/video/Les Experts/Les experts Las VegasS13E05.avi into a valid episode
Apr-23 20:38:58 ERROR    SHOWQUEUE-REFRESH :: Unable to parse the filename /volume1/video/Les Experts/Les experts Las VegasS13E01.avi into a valid episode
Apr-23 20:38:58 ERROR    SHOWQUEUE-REFRESH :: Unable to parse the filename /volume1/video/Les Experts/Les experts Las VegasS13E07.avi into a valid episode
Apr-23 20:38:58 ERROR    SHOWQUEUE-REFRESH :: Unable to parse the filename /volume1/video/Les Experts/Les experts Las VegasS13E06.avi into a valid episode
Apr-23 20:38:58 ERROR    SHOWQUEUE-REFRESH :: Unable to parse the filename /volume1/video/Les Experts/Les experts Las VegasS13E03.avi into a valid episode
Apr-23 20:38:58 INFO     SHOWQUEUE-REFRESH :: 72546: Loading all episodes from the show directory /volume1/video/Les Experts
Apr-23 20:38:58 INFO     SHOWQUEUE-REFRESH :: Performing refresh on Les Experts

Qu'en penses tu ?

**Comment by an0Nym0us63** [comment]
Il faut le meme nom que dans sick avant le sxxexx. Typiquement dans ce que je vois il te manque lespace avant le sxxexx au moins ca deja

---

De: Franck69 
Envoyé: mar., 23/04/2013 20:43
A: mozvip/Sick-Beard Sick-Beard@noreply.github.com
CC: sarakha63 sarakha_ludovic@yahoo.fr
Objet: Re: [Sick-Beard] Bug with T411 search (#69)

**Comment by Franck69** [comment]
excuse moi, je viens de faire un doublon, je voulais evité de mélanger tes
sujets...
 je viens d'ouvrir une issue

2013/4/23 sarakha63 notifications@github.com

**Comment by Franck69** [comment]
Effectivement!!!
quelle étourderie , je dis ca pour etre poli!!!
Merci beaucoup de prendre tant de temps pour des newbies comme moi!

ma deuxieme questions était qu'avec le Custom Search Names  Csi Las Vegas
je n'arrive pas à avoir d'episodes en telechargements, alors que sur
binnews, je trouve ce que je cherche, avec ce terme

2013/4/23 franck rainero franck.rainero@gmail.com

**Comment by an0Nym0us63** [comment]
Bon cool si maintenant il te les renomme. Je testerais mais pas aujourd'hui pour voir ce qui ne vas pas avec les custom search names et binnews

---

De: Franck69 
Envoyé: mar., 23/04/2013 21:31
A: mozvip/Sick-Beard Sick-Beard@noreply.github.com
CC: sarakha63 sarakha_ludovic@yahoo.fr
Objet: Re: [Sick-Beard] Bug with T411 search (#69)

**Comment by Franck69** [comment]
je ne m'attendais pas à ce que tu commence les investigations à 22h ^^
tu as une vie aussi, il me semble lol
Merci pour ton boulot

**Comment by an0Nym0us63** [comment]
^^
Jai deja une piste mais effectivement je stop pour ce soir

---

De: Franck69 
Envoyé: mar., 23/04/2013 22:01
A: mozvip/Sick-Beard Sick-Beard@noreply.github.com
CC: sarakha63 sarakha_ludovic@yahoo.fr
Objet: Re: [Sick-Beard] Bug with T411 search (#69)

> je ne m'attendais pas à ce que tu commence les investigations à 22h ^^ 
> tu as une vie aussi, il me semble lol 
> Merci pour ton boulot 
>

**Comment by lodoss5** [comment]
Bonjour,
Concernant le message: SEARCHQUEUE-MANUAL-SEARCH :: Ignoring result XXXXXXX s01e02 HDTV x264-TEAM VO because we don't want an episode that is SD TV
En général j'ai ce message quand je possède déjà l'épisode en question (ici s01e02), le message n'est pas adapté mais on n'a pas besoin du fichier.

**Comment by an0Nym0us63** [comment]
Oui je confirme qye sick fait ca en fait il est un peu adapté car si ct hd il le recupererais et ecraderais ton sd si tu lui avais demandé.  Il faut interpréter ca comme ignoring sd you already have

---

De: lodoss5 
Envoyé: mer., 24/04/2013 10:46
A: mozvip/Sick-Beard Sick-Beard@noreply.github.com
CC: sarakha63 sarakha_ludovic@yahoo.fr
Objet: Re: [Sick-Beard] Bug with T411 search (#69)

**Comment by arpheus** [comment]
D'accord, je vois le concept.
Merci :)
