### ISSUE TITLE
Le renommage oublie des sous-titres

### ISSUE THREAD

**Issue by FunFR** [mozvip/Sick-Beard#74]
Le process de renommage automatique des épisodes d'une série ne fonctionne par correctement pour les sous-titres.

Les sous-titres avec le même nom que l'épisode sont renommés correctement mais les sous-titres avec l'extension de la langue (ex : *.fr.srt) ne sont pas traités.

**Comment by an0Nym0us63** [comment]
tu parles de renommage demandé manuellement après ?

**Comment by FunFR** [comment]
Oui je parle du renommage manuel.
Par exemple en changeant le format du nom des fichiers dans SickBeard et en appliquant ce format ensuite.

**Comment by an0Nym0us63** [comment]
Ok on est bien daccord je vois le soucis

---

De: FunFR 
Envoyé: mer., 15/05/2013 09:56
A: mozvip/Sick-Beard Sick-Beard@noreply.github.com
CC: sarakha63 sarakha_ludovic@yahoo.fr
Objet: Re: [Sick-Beard] Le renommage oublie des sous-titres (#74)
