### ISSUE TITLE
Problème recherche manuelle

### ISSUE THREAD

**Issue by Franck69** [mozvip/Sick-Beard#75]
Salut,
Tout d'abord, merci pour le boulot que vous fournissez sur votre temps libre!
Je post encore un soucis que j'ai sur votre fork de Sickbeard, decidement, j'y tombe sur toutes ;)

Cela ce passe lorsque je tente de lancer un Téléchargement (Backlog) manuel sur un épisode de CSI...
Voilà les logs, en gros le fichier NZB est trouvé mais il ne l'envoie pas à SABNZBD ;(

Je vous ne cache pas que cela me dépasse quelque peu .....

Apr-27 19:01:06 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Unable to find a download for CSI - 12x19 - Frères de crime
Apr-27 19:01:06 ERROR    SEARCHQUEUE-MANUAL-SEARCH :: No NZB/Torrent providers found or enabled in the sickbeard config. Please check your settings.
AA
AAtimeout: timed out
AA    data = self._sock.recv(self._rbufsize)
AA  File "/usr/local/python/lib/python2.7/socket.py", line 447, in readline
AA    line = self.fp.readline()
AA  File "/usr/local/python/lib/python2.7/httplib.py", line 365, in _read_status
AA    version, status, reason = self._read_status()
AA  File "/usr/local/python/lib/python2.7/httplib.py", line 407, in begin
AA    response.begin()
AA  File "/usr/local/python/lib/python2.7/httplib.py", line 1030, in getresponse
AA    r = h.getresponse(buffering=True)
AA  File "/usr/local/python/lib/python2.7/urllib2.py", line 1180, in do_open
AA    return self.do_open(httplib.HTTPConnection, req)
AA  File "/usr/local/python/lib/python2.7/urllib2.py", line 1207, in http_open
AA    result = func(*args)
AA  File "/usr/local/python/lib/python2.7/urllib2.py", line 378, in _call_chain
AA    '_open', req)
AA  File "/usr/local/python/lib/python2.7/urllib2.py", line 418, in _open
AA    response = self._open(req, data)
AA  File "/usr/local/python/lib/python2.7/urllib2.py", line 400, in open
AA    return self.opener.open(request)
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/providers/binnewz/nzbdownloader.py", line 39, in open
AA    response = self.downloader.open(request)
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/providers/binnewz/nzbdownloader.py", line 54, in readRequest
AA    self.nzbdata = NZBSearchResult.readRequest( self, request )
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/providers/binnewz/nzbdownloader.py", line 73, in getNZB
AA    result.extraInfo = [item.getNZB() ]
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/providers/generic.py", line 284, in findEpisode
AA    curFoundResults = curProvider.findEpisode(episode, manualSearch=manualSearch)
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/search.py", line 304, in findEpisode
Apr-27 19:01:06 ERROR    SEARCHQUEUE-MANUAL-SEARCH :: Error while searching BinnewZ, skipping: timed out
Apr-27 18:59:57 INFO     SEARCHQUEUE-MANUAL-SEARCH :: BinNewz : Searching for CSI 12x19
Apr-27 18:59:57 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Found :  CSI.S12E19.FRENCH.720p.HDTV.x264-BAWLS  on NZBIndex
Apr-27 18:59:46 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Searching for download : Csi Las Vegas S12E19 , search string =  CSI.S12E19.FRENCH.720p.HDTV.x264-BAWLS  on NZBIndex
Apr-27 18:59:46 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Found : CSI.S12E19.FRENCH.HDTV.x264-BAWLS on NZBIndex
Apr-27 18:59:34 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Searching for download : Csi Las Vegas S12E19 , search string = CSI.S12E19.FRENCH.HDTV.x264-BAWLS on NZBIndex
Apr-27 18:59:32 INFO     SEARCHQUEUE-MANUAL-SEARCH :: BinNewz : Searching for CSI S12E19
Apr-27 18:59:31 INFO     SEARCHQUEUE-MANUAL-SEARCH :: BinNewz : Searching for Las Vegas 12x19
Apr-27 18:59:31 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Found :  CSI.S12E19.FRENCH.720p.HDTV.x264-BAWLS  on NZBIndex
Apr-27 18:59:20 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Searching for download : Csi Las Vegas S12E19 , search string =  CSI.S12E19.FRENCH.720p.HDTV.x264-BAWLS  on NZBIndex
Apr-27 18:59:20 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Found : les experts las vegas s12e19 on NZBIndex
Apr-27 18:59:08 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Searching for download : Les Experts Las Vegas S12-e19 , search string = les experts las vegas s12e19 on NZBIndex
Apr-27 18:59:08 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Found : CSI.S12E19.FRENCH.HDTV.x264-BAWLS on NZBIndex
Apr-27 18:58:57 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Searching for download : Csi Las Vegas S12E19 , search string = CSI.S12E19.FRENCH.HDTV.x264-BAWLS on NZBIndex
Apr-27 18:58:55 INFO     SEARCHQUEUE-MANUAL-SEARCH :: BinNewz : Searching for Las Vegas S12E19
Apr-27 18:58:54 INFO     SEARCHQUEUE-MANUAL-SEARCH :: BinNewz : Searching for  Csi Las Vegas 12x19
Apr-27 18:58:54 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Found :  CSI.S12E19.FRENCH.720p.HDTV.x264-BAWLS  on NZBIndex
Apr-27 18:58:42 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Searching for download : Csi Las Vegas S12E19 , search string =  CSI.S12E19.FRENCH.720p.HDTV.x264-BAWLS  on NZBIndex
Apr-27 18:58:42 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Found : CSI.S12E19.FRENCH.HDTV.x264-BAWLS on NZBIndex
Apr-27 18:58:28 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Searching for download : Csi Las Vegas S12E19 , search string = CSI.S12E19.FRENCH.HDTV.x264-BAWLS on NZBIndex
Apr-27 18:58:25 INFO     SEARCHQUEUE-MANUAL-SEARCH :: BinNewz : Searching for  Csi Las Vegas S12E19
Apr-27 18:58:24 INFO     SEARCHQUEUE-MANUAL-SEARCH :: BinNewz : Searching for CSI: Crime Scene Investigation 12x19
Apr-27 18:58:23 INFO     SEARCHQUEUE-MANUAL-SEARCH :: BinNewz : Searching for CSI: Crime Scene Investigation S12E19
Apr-27 18:58:22 INFO     SEARCHQUEUE-MANUAL-SEARCH :: BinNewz : Searching for CSI 12x19
Apr-27 18:58:22 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Found :  CSI.S12E19.FRENCH.720p.HDTV.x264-BAWLS  on NZBIndex
Apr-27 18:58:10 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Searching for download : Csi Las Vegas S12E19 , search string =  CSI.S12E19.FRENCH.720p.HDTV.x264-BAWLS  on NZBIndex
Apr-27 18:58:10 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Found : CSI.S12E19.FRENCH.HDTV.x264-BAWLS on NZBIndex
Apr-27 18:57:56 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Searching for download : Csi Las Vegas S12E19 , search string = CSI.S12E19.FRENCH.HDTV.x264-BAWLS on NZBIndex
Apr-27 18:57:54 INFO     SEARCHQUEUE-MANUAL-SEARCH :: BinNewz : Searching for CSI S12E19
Apr-27 18:57:54 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Searching BinnewZ for CSI - 12x19 - Frères de crime
Apr-27 18:57:54 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Searching for CSI - 12x19 - Frères de crime
Apr-27 18:57:54 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Searching for download for CSI - 12x19 - Frères de crime

**Comment by an0Nym0us63** [comment]
tu as un timeout car t'as ligne doit etre saturé au moment de la recherhche très courant comme soucis ( c'est que tu telecharges beaucoup a ce moment la)
