### ISSUE TITLE
Ajouter des provider pour Anime

### ISSUE THREAD

**Issue by Nonobis** [mozvip/Sick-Beard#77]
Salut,

Y'a t'il moyen d'ajouter quelques provider pour Anime ?

Notamant : 
- Animebyt --> http://animebyt.es
- BakaBT --> http://www.bakabt.me
- Tokyo Toshokan --> http://www.tokyotosho.info/

Merci par avance !

Et encore merci poour le fork, il est excellent !

**Comment by an0Nym0us63** [comment]
nous ne gerons pas la numérotation des animes pour l'instant donc le rajout des providers seraient inutile pour le moment
