### ISSUE TITLE
Improve xbmc metadata scrapper to work with XBMC Frodo

### ISSUE THREAD

**Issue by jgoret** [mozvip/Sick-Beard#82]
XBMC v12 (Frodo) a modifié le nommage des images associées aux séries et ajoute la possibilité d'avoir les poster ET les bannières. L'idée est d'améliorer le scrapper pour qu'il télécharge les images supplémentaires pour que les nouvelles versions d'XBMC puissent s'en servir.

Je m'occupe de faire ces modifications, je les aient déjà travaillée pour mon installation personnelle.

**Comment by an0Nym0us63** [comment]
fixed done
