### ISSUE TITLE
Erreur BinNewz

### ISSUE THREAD

**Issue by TechaY** [mozvip/Sick-Beard#97]
Bonsoir, 

Tout d'abord merci pour cette version VO/VF de sickbeard ! Tout simplement génial !! Je l'ai découvert hier, installé sur mon OSX Mountain Lion et "presque" tout fonctionne parfaitement. 

J'ai une erreur avec BinNewz à chaque recherche d'épisodes. Voici ce qu'affiche le log : 

2013-05-15 23:02:14.127407 SEARCHQUEUE-MANUAL-SEARCH :: Error trying to load BinNewz response: 
2013-05-15 23:02:15.957853 SEARCHQUEUE-MANUAL-SEARCH :: Error trying to load BinNewz response: 
2013-05-15 23:02:17.496171 SEARCHQUEUE-MANUAL-SEARCH :: Error trying to load BinNewz response: 
2013-05-15 23:02:19.020431 SEARCHQUEUE-MANUAL-SEARCH :: Error trying to load BinNewz response: 

Cela ne m'empêche pas de trouver mes épisodes grâce aux autres providers configurés mais je préfère l'indiquer. 

"HS: Il m'est impossible de récupérer des sous titres, peut importe le nombre de plugins sélectionnés. J'ai cru comprendre que cette recherche de sous titre fonctionnait avec subliminal. Subliminal est intégré à Sickbeard ou je dois le mettre en place sur ma machine ? "

**Comment by an0Nym0us63** [comment]
il me faudrait plus de detail sur ton erreur binnews ?

Pour subliminal non il est intégré, mais le framework est bancal donc ca recupere pas tout ce que ca pourrait mais pour ca faut voir le dev de subli. par contre qu'il t'en trouve aucun je suis perplexe quand meme

tu pourras donner des exmeples

**Comment by TechaY** [comment]
Alors ce 'est pas évident de donner plus de détails car j'en ai pas beaucoup sous la main... Pour chaque recherche (sans exeption) j'ai le droit à ces erreurs dans le log (à chaque fois au nombre de 4). 

Mes providers: http://sd-4.archive-host.com/membres/images/miniatures/89813518317216921/m2_provider.jpg

Peut importe l'ordre ou je mets Binnews, ces 4 erreurs sont toujours présente. 

Voici  ce que j'ai dans le log pour la recherche manuelle d'un épisode de game of thrones. : 

May-16 00:16:46 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Sending NZB to SABnzbd
May-16 00:16:46 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Downloading episode from https://www.smackdownonyou.com/getnzb/341db0c6cbcb83ddc8db853860561afa.nzb&i=5327&r=6a6c908aafb8b0d621fc09172625cbd7
May-16 00:16:46 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Quality of Game.of.Thrones.S03E06.720p.HDTV.x264-IMMERSE is HD TV
May-16 00:16:46 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Quality of Game.of.Thrones.S03E06.720p.HDTV.x264-IMMERSE is HD TV
May-16 00:16:46 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Quality of Game.of.Thrones.S03E06.INTERNAL.720p.HDTV.x264-EVOLVE is HD TV
May-16 00:16:46 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Quality of Game.of.Thrones.S03E06.The.Climb.720p.WEB-DL.DD5.1.H.264-NTb is 720p WEB-DL
May-16 00:16:46 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Quality of Game.of.Thrones.S03E06.The.Climb.1080p.WEB-DL.DD5.1.H.264-NTb is 1080p WEB-DL
May-16 00:16:46 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Quality of Game.of.Thrones.S03E06.INTERNAL.720p.HDTV.x264-EVOLVE is HD TV
May-16 00:16:46 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Quality of Game.of.Thrones.S03E06.720p.HDTV.x264.VOST-Kharn is HD TV
May-16 00:16:46 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Quality of Game.of.Thrones.S03E06.720p.HDTV.x264-IMMERSE is HD TV
May-16 00:16:46 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Quality of Game.of.Thrones.S03E06.INTERNAL.720p.HDTV.x264-EVOLVE is HD TV
May-16 00:16:46 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Quality of Game.of.Thrones.S03E06.The.Climb.1080p.WEB-DL.DD5.1.H.264-NTb is 1080p WEB-DL
May-16 00:16:46 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Quality of Game.of.Thrones.S03E06.INTERNAL.720p.HDTV.x264-EVOLVE is HD TV
May-16 00:16:46 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Quality of Game.of.Thrones.S03E06.720p.HDTV.x264.VOST-Kharn is HD TV
May-16 00:16:46 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Quality of Game.of.Thrones.S03E06.720p.HDTV.x264-IMMERSE is HD TV
May-16 00:16:46 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Quality of Game.of.Thrones.S03E06.INTERNAL.720p.HDTV.x264-EVOLVE is HD TV
May-16 00:16:46 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Quality of Game.of.Thrones.S03E06.720p.HDTV.x264-IMMERSE is HD TV
May-16 00:16:46 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Quality of Game.of.Thrones.S03E06.INTERNAL.720p.HDTV.x264-EVOLVE is HD TV
May-16 00:16:46 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Quality of Game.of.Thrones.S03E06.720p.HDTV.x264.VOST-Kharn is HD TV
May-16 00:16:45 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Clearing Sick Beard Index cache and updating with new information
May-16 00:16:42 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Searching Sick Beard Index for Game of Thrones - 3x06 - The Climb
May-16 00:16:40 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Clearing Usenet-Crawler cache and updating with new information
May-16 00:16:37 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Searching Usenet-Crawler for Game of Thrones - 3x06 - The Climb
May-16 00:16:35 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Clearing SmackDownOnYou cache and updating with new information
May-16 00:16:32 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Searching SmackDownOnYou for Game of Thrones - 3x06 - The Climb
May-16 00:16:32 ERROR    SEARCHQUEUE-MANUAL-SEARCH :: Error trying to load BinNewz response: 
May-16 00:16:31 INFO     SEARCHQUEUE-MANUAL-SEARCH :: BinNewz : Searching for Game of Thrones 3x6
May-16 00:16:31 ERROR    SEARCHQUEUE-MANUAL-SEARCH :: Error trying to load BinNewz response: 
May-16 00:16:30 INFO     SEARCHQUEUE-MANUAL-SEARCH :: BinNewz : Searching for Game of Thrones S03E06
May-16 00:16:30 ERROR    SEARCHQUEUE-MANUAL-SEARCH :: Error trying to load BinNewz response: 
May-16 00:16:29 INFO     SEARCHQUEUE-MANUAL-SEARCH :: BinNewz : Searching for Game of Thrones 3x6
May-16 00:16:29 ERROR    SEARCHQUEUE-MANUAL-SEARCH :: Error trying to load BinNewz response: 
May-16 00:16:27 INFO     SEARCHQUEUE-MANUAL-SEARCH :: BinNewz : Searching for Game of Thrones S03E06
May-16 00:16:27 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Searching BinnewZ for Game of Thrones - 3x06 - The Climb
May-16 00:16:25 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Clearing nzbndx cache and updating with new information
May-16 00:16:22 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Searching nzbndx for Game of Thrones - 3x06 - The Climb
May-16 00:16:20 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Clearing nzbX cache and updating with new information
May-16 00:16:18 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Searching nzbX for Game of Thrones - 3x06 - The Climb
May-16 00:16:18 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Searching for Game of Thrones - 3x06 - The Climb
May-16 00:16:18 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Searching for download for Game of Thrones - 3x06 - The Climb

**Comment by an0Nym0us63** [comment]
Hum, j'espère que cest pas une spécificité mac. Je my pencherais prochainement.

---

De: TechaY 
Envoyé: jeu., 16/05/2013 00:20
A: mozvip/Sick-Beard Sick-Beard@noreply.github.com
CC: sarakha63 sarakha_ludovic@yahoo.fr
Objet: Re: [Sick-Beard] Erreur BinNewz (#97)

**Comment by TechaY** [comment]
Ok Merci ;) Penses-tu que je devrais essayer de réinstaller Sick-Beard (il y a surement un autre terme non..? ^^) afin de voir si l'erreur est toujours présente ? 

Pour les sous titres, j'ai essayé sur 6 séries, ca ne fonctionne pas du tout. Je créer un autre sujet, ca sera plus simple.

**Comment by an0Nym0us63** [comment]
Pour que ni binnews ni les sous titre marche c bizarre. 

---

De: TechaY 
Envoyé: jeu., 16/05/2013 00:37
A: mozvip/Sick-Beard Sick-Beard@noreply.github.com
CC: sarakha63 sarakha_ludovic@yahoo.fr
Objet: Re: [Sick-Beard] Erreur BinNewz (#97)

**Comment by TechaY** [comment]
Oui.. j'avoue. Soit c'est du à l'os Mountain Lion, soit c'est mon installation qui a déconné. Je vais tout supprimé et recommencer afin de d'éliminer cette éventualité. 

Je te tiens au courant.

**Comment by an0Nym0us63** [comment]
Ca marche

---

De: TechaY 
Envoyé: jeu., 16/05/2013 00:47
A: mozvip/Sick-Beard Sick-Beard@noreply.github.com
CC: sarakha63 sarakha_ludovic@yahoo.fr
Objet: Re: [Sick-Beard] Erreur BinNewz (#97)

**Comment by TechaY** [comment]
Après une réinstallation de Cheetah-2.4.4 & Sick-Beard, aucun changement, toujours les mêmes problèmes évoqués plus haut. Cela doit donc venir de Mountain Lion...

**Comment by gdelcroix** [comment]
possible, passage de lion à montain lion (changement de mac) install neuve, j'ai ll'erreur binnewz depuis... je me demandais si j'avais merdé un truc ou si j'avais la poisse... je ne suis pas seul !

**Comment by TechaY** [comment]
ok donc ca confirme que cela vient surement de mountain lion. Tu as également des problèmes pour récupérer les sous titres ? As-tu déjà récupéré ne serait-ce qu'un seul fichier sous titre pour un épisode avec ta config actuelle ?
Impossible de mon coté, cela ne fonctionne pas.

**Comment by gdelcroix** [comment]
pas de soucis de sous titres pour moi

**Comment by gdelcroix** [comment]
@sarakha63 si tu as besoin de logs spécifiques, de résultats de tests pétrochimiques ou de statistiques de fusion thermonucléaire du moteur de sickbeard, ordonne et j'obéirai :)
et si je comprends pas la demande je le ferai savoir pour instructions plus détaillées ;)

**Comment by an0Nym0us63** [comment]
Ben la je vois pas car on a pas touché binnews sur ge point et je ne connais pas lunivers mac.

Par contre une log debug autour des erreurs pourraient mettre utile.

Je saurais ce qui cause le no response

**Comment by gdelcroix** [comment]
Le Log debug donne rien de plus que les deux lignes... Je pense que c'est peut être un souci avec la requête sql, mais j'ai pas de soft pour ouvrir la base et requeter, et j'ai pas non plus la requête envoyée par sickbeard a la db.
Je suis prêt a mettre les mains dans le cambouis si il faut... Il n'y a pas de trace de la requête dans le Log... Soit elle se forme mal, soit elle est pas envoyée, non ?

Envoyé de mon iPhone

**Comment by an0Nym0us63** [comment]
tu as forcement du debug autour de ERROR SEARCHQUEUE-MANUAL-SEARCH :: Error trying to load BinNewz response: 

Au pire regarde le fichier sickbeard.log

Pour moi rien a voir avec la requete. PS cela le fait il uiquement avec game of thrones ?

**Comment by gdelcroix** [comment]
Non si je n'active que binnewz comme provider, je n'ai aucun résultat et le même retour pour toutes les requêtes. Je suis pas chez moi ajd, je transmet une copie de mes logs demain soir :)

Envoyé de mon iPhone

**Comment by gdelcroix** [comment]
Voilà un bout de log plus complet...

May-23 01:09:40 ERROR    SEARCHQUEUE-BACKLOG-219341 :: Error trying to load BinNewz response: 
May-23 01:09:40 INFO     SEARCHQUEUE-BACKLOG-219341 :: BinNewz : Searching for Breakout Kings 1x13

j'ai donc suivi le 219341 voici l'extract de cet item

May-23 01:09:19 DEBUG    BACKLOG :: sickbeard.db: SELECT DISTINCT(season) as season FROM tv_episodes WHERE showid = ? AND season > 0 and airdate > ? with args [219341, 1]
May-23 01:09:21 INFO     BACKLOG :: Seeing if we need any episodes from Breakout Kings season 1
May-23 01:09:21 DEBUG    BACKLOG :: sickbeard.db: SELECT status FROM tv_episodes WHERE showid = ? AND season = ? with args [219341, 1]
May-23 01:09:22 INFO     BACKLOG :: Seeing if we need any episodes from Breakout Kings season 2
May-23 01:09:22 DEBUG    BACKLOG :: sickbeard.db: SELECT status FROM tv_episodes WHERE showid = ? AND season = ? with args [219341, 2]
May-23 01:09:22 DEBUG    BACKLOG :: Nothing in season 2 needs to be downloaded, skipping this season
May-23 01:09:23 DEBUG    BACKLOG :: sickbeard.db: SELECT DISTINCT(season) as season FROM tv_episodes WHERE showid = ? AND season > 0 and airdate > ? with args [80348, 1]
May-23 01:09:26 DEBUG    SEARCHQUEUE-BACKLOG-219341 :: sickbeard.db: SELECT episode FROM tv_episodes WHERE showid = ? AND season = ? with args [219341, 1]
May-23 01:09:26 INFO     BACKLOG :: Seeing if we need any episodes from Chuck season 1
May-23 01:09:26 DEBUG    BACKLOG :: sickbeard.db: SELECT status FROM tv_episodes WHERE showid = ? AND season = ? with args [80348, 1]
May-23 01:09:26 DEBUG    SEARCHQUEUE-BACKLOG-219341 :: Episode list: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
May-23 01:09:26 DEBUG    SEARCHQUEUE-BACKLOG-219341 :: sickbeard.db: SELECT status FROM tv_episodes WHERE showid = ? AND season = ? AND episode = ? with args [219341, 1, 1]
May-23 01:09:26 DEBUG    SEARCHQUEUE-BACKLOG-219341 :: sickbeard.db: SELECT status FROM tv_episodes WHERE showid = ? AND season = ? AND episode = ? with args [219341, 1, 2]
May-23 01:09:26 DEBUG    SEARCHQUEUE-BACKLOG-219341 :: sickbeard.db: SELECT status FROM tv_episodes WHERE showid = ? AND season = ? AND episode = ? with args [219341, 1, 3]
May-23 01:09:26 DEBUG    SEARCHQUEUE-BACKLOG-219341 :: sickbeard.db: SELECT status FROM tv_episodes WHERE showid = ? AND season = ? AND episode = ? with args [219341, 1, 4]
May-23 01:09:26 DEBUG    SEARCHQUEUE-BACKLOG-219341 :: sickbeard.db: SELECT status FROM tv_episodes WHERE showid = ? AND season = ? AND episode = ? with args [219341, 1, 5]
May-23 01:09:27 DEBUG    SEARCHQUEUE-BACKLOG-219341 :: sickbeard.db: SELECT status FROM tv_episodes WHERE showid = ? AND season = ? AND episode = ? with args [219341, 1, 6]
May-23 01:09:27 DEBUG    BACKLOG :: Nothing in season 1 needs to be downloaded, skipping this season
May-23 01:09:27 DEBUG    SEARCHQUEUE-BACKLOG-219341 :: sickbeard.db: SELECT status FROM tv_episodes WHERE showid = ? AND season = ? AND episode = ? with args [219341, 1, 7]
May-23 01:09:27 INFO     BACKLOG :: Seeing if we need any episodes from Chuck season 2
May-23 01:09:27 DEBUG    SEARCHQUEUE-BACKLOG-219341 :: sickbeard.db: SELECT status FROM tv_episodes WHERE showid = ? AND season = ? AND episode = ? with args [219341, 1, 8]
May-23 01:09:27 DEBUG    BACKLOG :: sickbeard.db: SELECT status FROM tv_episodes WHERE showid = ? AND season = ? with args [80348, 2]
May-23 01:09:27 DEBUG    SEARCHQUEUE-BACKLOG-219341 :: sickbeard.db: SELECT status FROM tv_episodes WHERE showid = ? AND season = ? AND episode = ? with args [219341, 1, 9]
May-23 01:09:27 DEBUG    SEARCHQUEUE-BACKLOG-219341 :: sickbeard.db: SELECT status FROM tv_episodes WHERE showid = ? AND season = ? AND episode = ? with args [219341, 1, 10]
May-23 01:09:27 DEBUG    BACKLOG :: Nothing in season 2 needs to be downloaded, skipping this season
May-23 01:09:27 INFO     BACKLOG :: Seeing if we need any episodes from Chuck season 3
May-23 01:09:27 DEBUG    SEARCHQUEUE-BACKLOG-219341 :: sickbeard.db: SELECT status FROM tv_episodes WHERE showid = ? AND season = ? AND episode = ? with args [219341, 1, 11]
May-23 01:09:27 DEBUG    BACKLOG :: sickbeard.db: SELECT status FROM tv_episodes WHERE showid = ? AND season = ? with args [80348, 3]
May-23 01:09:27 DEBUG    SEARCHQUEUE-BACKLOG-219341 :: sickbeard.db: SELECT status FROM tv_episodes WHERE showid = ? AND season = ? AND episode = ? with args [219341, 1, 12]
May-23 01:09:27 DEBUG    SEARCHQUEUE-BACKLOG-219341 :: sickbeard.db: SELECT status FROM tv_episodes WHERE showid = ? AND season = ? AND episode = ? with args [219341, 1, 13]
May-23 01:09:27 DEBUG    BACKLOG :: Nothing in season 3 needs to be downloaded, skipping this season
May-23 01:09:29 DEBUG    SEARCHQUEUE-BACKLOG-219341 :: Episode has no release name, replacing it with a generic one: %SN - %Sx%0E - %EN
May-23 01:09:30 INFO     BACKLOG :: Seeing if we need any episodes from Chuck season 4
May-23 01:09:30 DEBUG    SEARCHQUEUE-BACKLOG-219341 :: formatting pattern: %SN - %Sx%0E - %EN -> Breakout Kings - 1x13 - À la poursuite de Carmen Vega
May-23 01:09:30 DEBUG    BACKLOG :: sickbeard.db: SELECT status FROM tv_episodes WHERE showid = ? AND season = ? with args [80348, 4]
May-23 01:09:30 INFO     SEARCHQUEUE-BACKLOG-219341 :: Searching for Breakout Kings - 1x13 - À la poursuite de Carmen Vega
May-23 01:09:31 DEBUG    SEARCHQUEUE-BACKLOG-219341 :: Episode has no release name, replacing it with a generic one: %SN - %Sx%0E - %EN
May-23 01:09:31 DEBUG    SEARCHQUEUE-BACKLOG-219341 :: formatting pattern: %SN - %Sx%0E - %EN -> Breakout Kings - 1x13 - À la poursuite de Carmen Vega
May-23 01:09:31 INFO     SEARCHQUEUE-BACKLOG-219341 :: Searching BinnewZ for Breakout Kings - 1x13 - À la poursuite de Carmen Vega
May-23 01:09:32 DEBUG    SEARCHQUEUE-BACKLOG-219341 :: cache.db: SELECT time FROM lastUpdate WHERE provider = ? with args ['binnewz']
May-23 01:09:32 DEBUG    BACKLOG :: Nothing in season 5 needs to be downloaded, skipping this season
May-23 01:09:33 DEBUG    SEARCHQUEUE-BACKLOG-219341 :: cache.db: SELECT \* FROM binnewz WHERE tvdbid = ? AND season = ? AND episodes LIKE ? with args [219341, 1, '%|13|%']
May-23 01:09:33 DEBUG    BACKLOG :: Nothing in season 8 needs to be downloaded, skipping this season
May-23 01:09:33 DEBUG    BACKLOG :: sickbeard.db: SELECT DISTINCT(season) as season FROM tv_episodes WHERE showid = ? AND season > 0 and airdate > ? with args [82066, 1]
May-23 01:09:33 DEBUG    SEARCHQUEUE-BACKLOG-219341 :: Cache results: []
May-23 01:09:33 DEBUG    SEARCHQUEUE-BACKLOG-219341 :: cache.db: SELECT show_name FROM scene_exceptions WHERE tvdb_id = ? with args [219341]
May-23 01:09:33 INFO     SEARCHQUEUE-BACKLOG-219341 :: BinNewz : Searching for Breakout Kings S01E13
May-23 01:09:40 ERROR    SEARCHQUEUE-BACKLOG-219341 :: Error trying to load BinNewz response: 
May-23 01:09:40 INFO     SEARCHQUEUE-BACKLOG-219341 :: BinNewz : Searching for Breakout Kings 1x13
May-23 01:09:43 ERROR    SEARCHQUEUE-BACKLOG-219341 :: Error trying to load BinNewz response: 
May-23 01:09:43 INFO     SEARCHQUEUE-BACKLOG-219341 :: BinNewz : Searching for Breakout Kings S01E13
May-23 01:09:46 ERROR    SEARCHQUEUE-BACKLOG-219341 :: Error trying to load BinNewz response: 
May-23 01:09:46 INFO     SEARCHQUEUE-BACKLOG-219341 :: BinNewz : Searching for Breakout Kings 1x13
May-23 01:09:49 ERROR    SEARCHQUEUE-BACKLOG-219341 :: Error trying to load BinNewz response: 
May-23 01:09:49 DEBUG    SEARCHQUEUE-BACKLOG-219341 :: Picking the best result out of []
May-23 01:09:49 DEBUG    SEARCHQUEUE-BACKLOG-219341 :: sickbeard.db: SELECT episode_id from tv_episodes where tvdbid=? with args [3461691]
May-23 01:09:49 DEBUG    SEARCHQUEUE-BACKLOG-219341 :: sickbeard.db: SELECT link from episode_links where episode_id=? with args [15]
May-23 01:09:49 DEBUG    SEARCHQUEUE-BACKLOG-219341 :: No result picked.

qui s'enchaine avec

May-23 01:09:55 DEBUG    SEARCHQUEUE-BACKLOG-80348 :: sickbeard.db: SELECT episode FROM tv_episodes WHERE showid = ? AND season = ? with args [80348, 5]
May-23 01:09:55 DEBUG    SEARCHQUEUE-BACKLOG-80348 :: Episode list: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
May-23 01:09:55 DEBUG    SEARCHQUEUE-BACKLOG-80348 :: sickbeard.db: SELECT status FROM tv_episodes WHERE showid = ? AND season = ? AND episode = ? with args [80348, 5, 1]
May-23 01:09:55 DEBUG    SEARCHQUEUE-BACKLOG-80348 :: sickbeard.db: SELECT status FROM tv_episodes WHERE showid = ? AND season = ? AND episode = ? with args [80348, 5, 2]
May-23 01:09:55 DEBUG    SEARCHQUEUE-BACKLOG-80348 :: sickbeard.db: SELECT status FROM tv_episodes WHERE showid = ? AND season = ? AND episode = ? with args [80348, 5, 3]
May-23 01:09:55 DEBUG    SEARCHQUEUE-BACKLOG-80348 :: sickbeard.db: SELECT status FROM tv_episodes WHERE showid = ? AND season = ? AND episode = ? with args [80348, 5, 4]
May-23 01:09:55 DEBUG    SEARCHQUEUE-BACKLOG-80348 :: sickbeard.db: SELECT status FROM tv_episodes WHERE showid = ? AND season = ? AND episode = ? with args [80348, 5, 5]
May-23 01:09:55 DEBUG    SEARCHQUEUE-BACKLOG-80348 :: sickbeard.db: SELECT status FROM tv_episodes WHERE showid = ? AND season = ? AND episode = ? with args [80348, 5, 6]
May-23 01:09:55 DEBUG    SEARCHQUEUE-BACKLOG-80348 :: sickbeard.db: SELECT status FROM tv_episodes WHERE showid = ? AND season = ? AND episode = ? with args [80348, 5, 7]
May-23 01:09:55 DEBUG    SEARCHQUEUE-BACKLOG-80348 :: sickbeard.db: SELECT status FROM tv_episodes WHERE showid = ? AND season = ? AND episode = ? with args [80348, 5, 8]
May-23 01:09:55 DEBUG    SEARCHQUEUE-BACKLOG-80348 :: sickbeard.db: SELECT status FROM tv_episodes WHERE showid = ? AND season = ? AND episode = ? with args [80348, 5, 9]
May-23 01:09:55 DEBUG    SEARCHQUEUE-BACKLOG-80348 :: sickbeard.db: SELECT status FROM tv_episodes WHERE showid = ? AND season = ? AND episode = ? with args [80348, 5, 10]
May-23 01:09:55 DEBUG    SEARCHQUEUE-BACKLOG-80348 :: sickbeard.db: SELECT status FROM tv_episodes WHERE showid = ? AND season = ? AND episode = ? with args [80348, 5, 11]
May-23 01:09:55 DEBUG    SEARCHQUEUE-BACKLOG-80348 :: sickbeard.db: SELECT status FROM tv_episodes WHERE showid = ? AND season = ? AND episode = ? with args [80348, 5, 12]
May-23 01:09:55 DEBUG    SEARCHQUEUE-BACKLOG-80348 :: sickbeard.db: SELECT status FROM tv_episodes WHERE showid = ? AND season = ? AND episode = ? with args [80348, 5, 13]
May-23 01:09:55 INFO     SEARCHQUEUE-BACKLOG-80348 :: Searching for stuff we need from Chuck season 5
May-23 01:09:55 DEBUG    SEARCHQUEUE-BACKLOG-80348 :: cache.db: SELECT show_name FROM scene_exceptions WHERE tvdb_id = ? with args [80348]
May-23 01:09:55 INFO     SEARCHQUEUE-BACKLOG-80348 :: BinNewz : Searching for Chuck.saison  5
May-23 01:09:57 ERROR    SEARCHQUEUE-BACKLOG-80348 :: Error trying to load BinNewz response: 
May-23 01:09:57 INFO     SEARCHQUEUE-BACKLOG-80348 :: BinNewz : Searching for Chuck.saison  5
May-23 01:09:59 ERROR    SEARCHQUEUE-BACKLOG-80348 :: Error trying to load BinNewz response: 
May-23 01:09:59 DEBUG    SEARCHQUEUE-BACKLOG-80348 :: The highest quality of any match is N/A

ou encore May-23 01:10:01 DEBUG    SEARCHQUEUE-BACKLOG-185851 :: sickbeard.db: SELECT episode FROM tv_episodes WHERE showid = ? AND season = ? with args [185851, 1]
May-23 01:10:01 DEBUG    SEARCHQUEUE-BACKLOG-185851 :: Episode list: [1, 2, 3, 4, 5, 6, 7, 8]
May-23 01:10:01 DEBUG    SEARCHQUEUE-BACKLOG-185851 :: sickbeard.db: SELECT status FROM tv_episodes WHERE showid = ? AND season = ? AND episode = ? with args [185851, 1, 1]
May-23 01:10:01 DEBUG    SEARCHQUEUE-BACKLOG-185851 :: sickbeard.db: SELECT status FROM tv_episodes WHERE showid = ? AND season = ? AND episode = ? with args [185851, 1, 2]
May-23 01:10:01 DEBUG    SEARCHQUEUE-BACKLOG-185851 :: sickbeard.db: SELECT status FROM tv_episodes WHERE showid = ? AND season = ? AND episode = ? with args [185851, 1, 3]
May-23 01:10:01 DEBUG    SEARCHQUEUE-BACKLOG-185851 :: sickbeard.db: SELECT status FROM tv_episodes WHERE showid = ? AND season = ? AND episode = ? with args [185851, 1, 4]
May-23 01:10:01 DEBUG    SEARCHQUEUE-BACKLOG-185851 :: sickbeard.db: SELECT status FROM tv_episodes WHERE showid = ? AND season = ? AND episode = ? with args [185851, 1, 5]
May-23 01:10:01 DEBUG    SEARCHQUEUE-BACKLOG-185851 :: sickbeard.db: SELECT status FROM tv_episodes WHERE showid = ? AND season = ? AND episode = ? with args [185851, 1, 6]
May-23 01:10:01 DEBUG    SEARCHQUEUE-BACKLOG-185851 :: sickbeard.db: SELECT status FROM tv_episodes WHERE showid = ? AND season = ? AND episode = ? with args [185851, 1, 7]
May-23 01:10:01 DEBUG    SEARCHQUEUE-BACKLOG-185851 :: sickbeard.db: SELECT status FROM tv_episodes WHERE showid = ? AND season = ? AND episode = ? with args [185851, 1, 8]
May-23 01:10:04 DEBUG    SEARCHQUEUE-BACKLOG-185851 :: sickbeard.db: SELECT episode FROM tv_episodes WHERE showid = ? AND season = ? with args [185851, 2]
May-23 01:10:04 DEBUG    SEARCHQUEUE-BACKLOG-185851 :: Episode list: [1, 2, 3, 4, 5, 6, 7, 8]
May-23 01:10:04 DEBUG    SEARCHQUEUE-BACKLOG-185851 :: sickbeard.db: SELECT status FROM tv_episodes WHERE showid = ? AND season = ? AND episode = ? with args [185851, 2, 1]
May-23 01:10:04 DEBUG    SEARCHQUEUE-BACKLOG-185851 :: sickbeard.db: SELECT status FROM tv_episodes WHERE showid = ? AND season = ? AND episode = ? with args [185851, 2, 2]
May-23 01:10:04 DEBUG    SEARCHQUEUE-BACKLOG-185851 :: sickbeard.db: SELECT status FROM tv_episodes WHERE showid = ? AND season = ? AND episode = ? with args [185851, 2, 3]
May-23 01:10:04 DEBUG    SEARCHQUEUE-BACKLOG-185851 :: sickbeard.db: SELECT status FROM tv_episodes WHERE showid = ? AND season = ? AND episode = ? with args [185851, 2, 4]
May-23 01:10:04 DEBUG    SEARCHQUEUE-BACKLOG-185851 :: sickbeard.db: SELECT status FROM tv_episodes WHERE showid = ? AND season = ? AND episode = ? with args [185851, 2, 5]
May-23 01:10:04 DEBUG    SEARCHQUEUE-BACKLOG-185851 :: sickbeard.db: SELECT status FROM tv_episodes WHERE showid = ? AND season = ? AND episode = ? with args [185851, 2, 6]
May-23 01:10:04 DEBUG    SEARCHQUEUE-BACKLOG-185851 :: sickbeard.db: SELECT status FROM tv_episodes WHERE showid = ? AND season = ? AND episode = ? with args [185851, 2, 7]
May-23 01:10:04 DEBUG    SEARCHQUEUE-BACKLOG-185851 :: sickbeard.db: SELECT status FROM tv_episodes WHERE showid = ? AND season = ? AND episode = ? with args [185851, 2, 8]
May-23 01:10:04 INFO     SEARCHQUEUE-BACKLOG-185851 :: Searching for stuff we need from Maison close season 2
May-23 01:10:04 DEBUG    SEARCHQUEUE-BACKLOG-185851 :: cache.db: SELECT show_name FROM scene_exceptions WHERE tvdb_id = ? with args [185851]
May-23 01:10:04 INFO     SEARCHQUEUE-BACKLOG-185851 :: BinNewz : Searching for Maison close.saison  2
May-23 01:10:05 ERROR    SEARCHQUEUE-BACKLOG-185851 :: Error trying to load BinNewz response: 
May-23 01:10:06 INFO     SEARCHQUEUE-BACKLOG-185851 :: BinNewz : Searching for Maison Close.saison  2
May-23 01:10:07 ERROR    SEARCHQUEUE-BACKLOG-185851 :: Error trying to load BinNewz response: 
May-23 01:10:07 DEBUG    SEARCHQUEUE-BACKLOG-185851 :: The highest quality of any match is N/A

**Comment by gdelcroix** [comment]
up, j'ai peut être un élément complémentaire, l'utf-8 serait le chat noir dans l'histoire...
je m'explique: j'avais un souci de dossiers invisibles en NFS depuis le MAC alors que OK depuis un PC, et suite à tests, croisements de données, recherches gogol, ssh et vi... ces c**s de chez apple sont (presque) les seuls a utiliser l'UTF-8 NFD et le reste du monde l'UTF-8 NFC
j'ai du forcer dans nfs.conf le NFC pour qu'il le prenne en compte comme table de caractère et m'affiche enfin mes dossiers et fichiers, peut être est-ce le même problème ?

**Comment by gdelcroix** [comment]
?
